const state={data:null,measurements:JSON.parse(localStorage.getItem('aq_measurements')||'[]'),maintenance:JSON.parse(localStorage.getItem('aq_maintenance')||'[]'),view:'home'};
const $=s=>document.querySelector(s);const main=$('#mainContent');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmtDate=v=>new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));

async function boot(){
  const res=await fetch('data/aquarium.json',{cache:'no-store'});state.data=await res.json();
  hydrateParameters();bindGlobal();render();
  if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
}
function hydrateParameters(){for(const p of state.data.parameters){const last=[...state.measurements].reverse().find(m=>m.key===p.key);if(last)p.latest=last;}
 const select=$('#measurementType');select.innerHTML=state.data.parameters.map(p=>`<option value="${p.key}">${p.name} (${p.unit||'valor'})</option>`).join('');}
function bindGlobal(){
 document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));render();scrollTo({top:0,behavior:'smooth'})});
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
 $('#measurementForm').onsubmit=e=>{e.preventDefault();const key=$('#measurementType').value;const value=Number($('#measurementValue').value);const note=$('#measurementNote').value.trim();state.measurements.push({key,value,note,at:new Date().toISOString()});localStorage.setItem('aq_measurements',JSON.stringify(state.measurements));hydrateParameters();e.target.reset();$('#measurementDialog').close();render();};
 $('#maintenanceForm').onsubmit=e=>{e.preventDefault();state.maintenance.push({type:$('#maintenanceType').value,detail:$('#maintenanceDetail').value.trim(),at:new Date().toISOString()});localStorage.setItem('aq_maintenance',JSON.stringify(state.maintenance));e.target.reset();$('#maintenanceDialog').close();render();};
 $('#healthButton').onclick=()=>{state.view='advisor';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='advisor'));render();};
}
function render(){if(!state.data)return;const views={home:homeView,livestock:livestockView,parameters:parametersView,equipment:equipmentView,advisor:advisorView};main.innerHTML=views[state.view]();bindDynamic();updateHealth();}
function health(){const have=state.data.parameters.filter(p=>p.latest).length;const high=state.data.risks.filter(r=>r.severity==='high').length;if(have<4)return{label:'Sin línea base',score:42,tone:'warn'};if(high)return{label:'En recuperación',score:58,tone:'warn'};return{label:'Estable',score:82,tone:'ok'};}
function updateHealth(){const h=health();$('#healthLabel').textContent=h.label;$('.health-dot').style.background=h.tone==='ok'?'var(--green)':'var(--amber)';}
function homeView(){const h=health(),alive=state.data.livestock.filter(x=>x.status==='alive').reduce((a,x)=>a+(x.count||1),0),broken=state.data.equipment.filter(x=>x.status==='broken').length,last=state.maintenance.at(-1);return `
 <section class="hero"><div class="hero-row"><div><p class="eyebrow">ESTADO GENERAL</p><h2>${h.label}</h2><p class="muted">Primera fase: medir antes de comprar.</p></div><div class="score">${h.score}<small>/100</small></div></div></section>
 <div class="grid">
  <article class="card"><h3>Habitantes</h3><div class="metric">${alive}<small> estimados</small></div><p class="muted">${state.data.livestock.length} fichas</p></article>
  <article class="card"><h3>Parámetros</h3><div class="metric">${state.data.parameters.filter(p=>p.latest).length}<small> / ${state.data.parameters.length}</small></div><p class="muted">línea base</p></article>
  <article class="card"><h3>Equipo</h3><div class="metric">${state.data.equipment.length}</div><p class="muted">${broken} averiados</p></article>
  <article class="card"><h3>Corales</h3><div class="metric">0</div><p class="muted">fase de recuperación</p></article>
 </div>
 <div class="quick-actions"><button class="action" data-action="measurement">＋ Medición</button><button class="action" data-action="maintenance">✓ Mantenimiento</button></div>
 <div class="section-title"><div><p>PRIORIDAD</p><h2>Lo siguiente</h2></div></div>
 <article class="card full advisor-card"><div class="priority">IA · ACCIÓN Nº 1</div><h3>Crear la analítica Día 0</h3><p>Ya tienes medidores suficientes para empezar. Registra temperatura, salinidad, fosfato y nitrato. Con esos cuatro datos cambiaremos recomendaciones genéricas por decisiones basadas en tu acuario.</p><span class="source-pill">sin compra</span><span class="source-pill">alta prioridad</span></article>
 <div class="section-title"><div><p>RIESGOS CONOCIDOS</p><h2>Vigilancia</h2></div></div>
 <div class="entity-list">${state.data.risks.slice(0,3).map(r=>`<div class="card"><h3>${esc(r.title)}</h3><p class="muted">${esc(r.reason)}</p><span class="badge ${r.severity==='high'?'danger':'warn'}">${r.severity==='high'?'ALTO':'MEDIO'}</span></div>`).join('')}</div>
 ${last?`<div class="section-title"><div><p>ÚLTIMO REGISTRO</p><h2>Mantenimiento</h2></div></div><div class="timeline-item"><strong>${esc(last.type)}</strong><small>${fmtDate(last.at)} · ${esc(last.detail||'sin detalle')}</small></div>`:''}`}
function livestockView(){return `<div class="section-title"><div><p>INVENTARIO VIVO</p><h2>Habitantes</h2></div><p>Toca para abrir ficha</p></div><div class="entity-list">${state.data.livestock.map(x=>entityRow(x,'livestock')).join('')}</div><div class="card full" style="margin-top:14px"><h3>Regla de identificación</h3><p class="muted">Las especies dudosas permanecen como provisionales. Una foto nueva puede aumentar la confianza sin sobrescribir el historial.</p></div>`}
function equipmentView(){const groups=[['filtration','Filtración'],['flow','Movimiento'],['skimmer','Skimmer'],['lighting','Iluminación'],['topoff','Reposición'],['test','Medición']];return `<div class="section-title"><div><p>INVENTARIO TÉCNICO</p><h2>Equipo</h2></div><p>${state.data.equipment.length} registros</p></div>${groups.map(([k,n])=>{const xs=state.data.equipment.filter(x=>x.category===k);return xs.length?`<div class="section-title"><div><p>${n.toUpperCase()}</p></div></div><div class="entity-list">${xs.map(x=>entityRow(x,'equipment')).join('')}</div>`:''}).join('')}`}
function parametersView(){return `<div class="section-title"><div><p>QUÍMICA Y ESTABILIDAD</p><h2>Agua</h2></div><p>${state.data.parameters.filter(p=>p.latest).length}/${state.data.parameters.length} medidos</p></div><div class="card full">${state.data.parameters.map(p=>`<div class="param-row"><div><div class="param-name">${esc(p.name)}</div><small class="muted">Objetivo ${esc(p.target)} ${esc(p.unit)}</small></div><div class="param-value">${p.latest?esc(p.latest.value):'—'} <small>${esc(p.unit)}</small></div><div class="param-date">${p.latest?fmtDate(p.latest.at):'sin medir'}</div></div>`).join('')}</div><div class="quick-actions"><button class="primary" data-action="measurement">＋ Registrar medición</button></div>${state.measurements.length?`<div class="section-title"><div><p>HISTORIAL LOCAL</p><h2>Últimas mediciones</h2></div></div><div class="timeline">${[...state.measurements].reverse().slice(0,8).map(m=>{const p=state.data.parameters.find(x=>x.key===m.key);return `<div class="timeline-item"><strong>${esc(p?.name)} · ${esc(m.value)} ${esc(p?.unit)}</strong><small>${fmtDate(m.at)} ${m.note?'· '+esc(m.note):''}</small></div>`}).join('')}</div>`:''}`}
function advisorView(){const missing=state.data.parameters.filter(p=>!p.latest).slice(0,4);return `<div class="section-title"><div><p>REEF ADVISOR</p><h2>IA del acuario</h2></div><p>v0.1</p></div>
 <article class="card advisor-card"><div class="priority">DECISIÓN ACTUAL</div><h3>No comprar coral todavía</h3><p>Faltan datos de línea base y siguen abiertos tres problemas físicos: temperatura estival, reposición averiada y skimmer. La prioridad es medir y reparar, no aumentar carga biológica.</p><span class="source-pill">confianza alta</span><span class="source-pill">coste 0 € ahora</span></article>
 <div class="section-title"><div><p>DATOS QUE FALTAN</p><h2>Para decidir mejor</h2></div></div><div class="card">${missing.length?missing.map(p=>`<div class="param-row"><div class="param-name">${esc(p.name)}</div><div></div><div class="param-date">pendiente</div></div>`).join(''):'Línea base suficiente para la siguiente evaluación.'}</div>
 <div class="section-title"><div><p>COMPRA INTELIGENTE</p><h2>Motor de recomendación</h2></div></div><div class="card"><h3>Antes de sugerir un producto</h3><p class="muted">La app comprobará inventario, necesidad, compatibilidad con 130 L, medidas disponibles, mantenimiento, precio actual y fuentes. “No comprar” será una recomendación válida.</p></div>
 <div class="section-title"><div><p>AUTOMATIZACIONES CAPTURADAS</p><h2>Luz y flujo</h2></div></div><div class="card"><h3>AI Nero 5</h3><p class="muted">Modo observado: ${esc(state.data.automation.nero5.mode)} · referencia ${esc(state.data.automation.nero5.referencePercent)}%. Horario exacto pendiente de confirmación.</p></div><div class="card" style="margin-top:10px"><h3>Fluval Marine</h3><p class="muted">${esc(state.data.automation.lighting.observed)}</p></div>`}
function entityRow(x,type){const status=x.status==='broken'?['Averiado','danger']:x.status==='working'?['Funciona','']:x.status==='alive'?['Vivo','']:['Por verificar','warn'];return `<button class="entity" data-entity-type="${type}" data-entity-id="${x.id}"><div class="avatar">${x.emoji||iconFor(x.category)}</div><div style="min-width:0"><h3>${esc(x.commonName||x.name)}</h3><p>${esc(x.scientificName||x.model||x.category||'')}</p><span class="badge ${status[1]}">${status[0]}</span>${x.confidence<.8?` <span class="badge warn">ID ${Math.round(x.confidence*100)}%</span>`:''}</div></button>`}
function iconFor(c){return({filtration:'◫',flow:'≈',skimmer:'◌',lighting:'☀',topoff:'💧',test:'⌁'}[c]||'⚙')}
function bindDynamic(){main.querySelectorAll('[data-action="measurement"]').forEach(b=>b.onclick=()=>$('#measurementDialog').showModal());main.querySelectorAll('[data-action="maintenance"]').forEach(b=>b.onclick=()=>$('#maintenanceDialog').showModal());main.querySelectorAll('[data-entity-id]').forEach(b=>b.onclick=()=>showEntity(b.dataset.entityType,b.dataset.entityId));}
function showEntity(type,id){const x=(type==='livestock'?state.data.livestock:state.data.equipment).find(v=>v.id===id);if(!x)return;const title=x.commonName||x.name;const dlg=$('#entityDialog'),content=$('#entityDialogContent');content.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">FICHA REAL</p><h2>${esc(title)}</h2></div><button class="icon-btn" id="closeEntity">×</button></div><div class="detail-hero"><div class="avatar">${x.emoji||iconFor(x.category)}</div><div><strong>${esc(x.scientificName||x.model||'')}</strong><p class="muted">Confianza del registro: ${Math.round((x.confidence??1)*100)}%</p></div></div><div class="detail-grid">${type==='livestock'?`<div class="detail-stat"><small>Cantidad</small><strong>${esc(x.count)}${x.countIsEstimate?' aprox.':''}</strong></div><div class="detail-stat"><small>Tienda</small><strong>${esc(x.shop||'Pendiente')}</strong></div><div class="detail-stat"><small>Precio compra</small><strong>${x.purchasePrice??'Pendiente'}</strong></div><div class="detail-stat"><small>Precio mercado</small><strong>${x.marketPrice??'Pendiente de búsqueda'}</strong></div>`:`<div class="detail-stat"><small>Estado</small><strong>${esc(x.status)}</strong></div><div class="detail-stat"><small>Categoría</small><strong>${esc(x.category)}</strong></div>`}</div><div class="card"><h3>Notas</h3><p class="muted">${esc(x.notes||'Sin notas')}</p></div>`;$('#closeEntity').onclick=()=>dlg.close();dlg.showModal();}
boot().catch(err=>{main.innerHTML=`<div class="empty">No se pudo cargar el inventario. ${esc(err.message)}</div>`});
