const state={data:null,measurements:JSON.parse(localStorage.getItem('aq_measurements')||'[]'),maintenance:JSON.parse(localStorage.getItem('aq_maintenance')||'[]'),view:'home'};
const $=s=>document.querySelector(s);const main=$('#mainContent');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmtDate=v=>new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const euro=v=>v==null?'Pendiente':new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v);
async function boot(){const res=await fetch('data/aquarium.json',{cache:'no-store'});state.data=await res.json();hydrateParameters();bindGlobal();render();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
function hydrateParameters(){for(const p of state.data.parameters){const last=[...state.measurements].reverse().find(m=>m.key===p.key);if(last)p.latest=last;}$('#measurementType').innerHTML=state.data.parameters.map(p=>`<option value="${p.key}">${p.name} (${p.unit||'valor'})</option>`).join('');}
function bindGlobal(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$('#measurementForm').onsubmit=e=>{e.preventDefault();const key=$('#measurementType').value,value=Number($('#measurementValue').value),note=$('#measurementNote').value.trim();state.measurements.push({key,value,note,at:new Date().toISOString()});localStorage.setItem('aq_measurements',JSON.stringify(state.measurements));hydrateParameters();e.target.reset();$('#measurementDialog').close();render();};$('#maintenanceForm').onsubmit=e=>{e.preventDefault();state.maintenance.push({type:$('#maintenanceType').value,detail:$('#maintenanceDetail').value.trim(),at:new Date().toISOString()});localStorage.setItem('aq_maintenance',JSON.stringify(state.maintenance));e.target.reset();$('#maintenanceDialog').close();render();};$('#healthButton').onclick=()=>go('advisor');}
function go(view){state.view=view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));render();scrollTo({top:0,behavior:'smooth'});}
function render(){const views={home:homeView,livestock:livestockView,parameters:parametersView,equipment:equipmentView,advisor:advisorView};main.innerHTML=views[state.view]();bindDynamic();updateHealth();}
function health(){const have=state.data.parameters.filter(p=>p.latest).length;if(have<4)return{label:'Pendiente de analítica',score:42,tone:'warn'};if(state.data.risks.some(r=>r.severity==='high'))return{label:'En recuperación',score:58,tone:'warn'};return{label:'Estable',score:82,tone:'ok'};}
function updateHealth(){const h=health();$('#healthLabel').textContent=h.label;$('.health-dot').style.background=h.tone==='ok'?'var(--green)':'var(--amber)';}
function totalAlive(){return state.data.livestock.filter(x=>x.status==='alive').reduce((a,x)=>a+(x.count||1),0)}
function homeView(){const h=health(),measured=state.data.parameters.filter(p=>p.latest).length;return `<section class="dashboard-head"><div><p class="kicker">TU ACUARIO</p><h2>Reef 130</h2><p>Sevilla · Marino · activo desde ~2023</p></div><div class="health-ring"><strong>${h.score}</strong><span>/100</span></div></section>
<section class="today-card"><div class="today-top"><div><span class="status-dot"></span><b>${h.label}</b></div><span>${measured}/8 parámetros</span></div><h3>Hoy solo necesito 4 datos tuyos</h3><p>Temperatura, salinidad, fosfato y nitrato. No compres nada antes de esta primera lectura.</p><button class="primary compact" data-action="measurement">Registrar ahora</button></section>
<div class="section-title"><div><p>VISTA RÁPIDA</p><h2>Habitantes</h2></div><button class="text-btn" data-go="livestock">Ver todos</button></div>
<div class="livestock-strip">${state.data.livestock.map(x=>livestockMini(x)).join('')}</div>
<div class="section-title"><div><p>CONTROL</p><h2>Lo importante</h2></div></div>
<div class="control-list"><button class="control-card" data-go="parameters"><span class="control-icon">⌁</span><div><b>Agua</b><small>${measured?`${measured} parámetros registrados`:'Sin analítica inicial'}</small></div><span>›</span></button><button class="control-card" data-go="equipment"><span class="control-icon">⚙</span><div><b>Equipo</b><small>${state.data.equipment.filter(x=>x.status==='broken').length} incidencias abiertas</small></div><span>›</span></button><button class="control-card" data-go="advisor"><span class="control-icon">✦</span><div><b>Reef Advisor</b><small>Plan personalizado y compras</small></div><span>›</span></button></div>`}
function livestockMini(x){return `<button class="mini-fish" data-entity-type="livestock" data-entity-id="${x.id}"><div class="mini-photo">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.commonName)}">`:`<span>${x.kind==='invertebrate'?'🐌':'🐟'}</span>`}<em>${x.countIsEstimate?`${x.countMin}–${x.countMax}`:`×${x.count}`}</em></div><b>${esc(x.commonName)}</b><small>${esc(x.scientificName)}</small></button>`}
function livestockView(){return `<div class="page-intro"><p class="kicker">INVENTARIO VIVO</p><h2>${totalAlive()} animales registrados</h2><p>Cada ficha mantiene cantidad, sexo, origen, precio, estado e historial.</p></div><div class="life-grid">${state.data.livestock.map(x=>livestockCard(x)).join('')}</div><article class="info-card"><b>Próximo paso visual</b><p>Las fotos propias del acuario sustituirán progresivamente a las imágenes de referencia. Después podemos incorporar modelos 3D donde aporte valor, sin sacrificar velocidad.</p></article>`}
function livestockCard(x){const sex=x.individuals?.map(i=>i.label).join(' + ');return `<button class="life-card" data-entity-type="livestock" data-entity-id="${x.id}"><div class="life-photo">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.commonName)}">`:`<div class="placeholder-fish">${x.kind==='invertebrate'?'🐌':'🐟'}</div>`}<span class="count-badge">${x.countIsEstimate?`${x.countMin}–${x.countMax}`:`${x.count} ud.`}</span></div><div class="life-body"><div class="life-title"><div><h3>${esc(x.commonName)}</h3><p>${esc(x.scientificName)}</p></div><span>›</span></div>${sex?`<div class="micro-pill">${esc(sex)}</div>`:''}<div class="life-meta"><span>${esc(x.shop||'Tienda pendiente')}</span><span>${x.purchaseSize?`Talla compra ${esc(x.purchaseSize)}`:'Talla pendiente'}</span></div></div></button>`}
function parametersView(){const measured=state.data.parameters.filter(p=>p.latest).length;return `<div class="page-intro"><p class="kicker">AGUA</p><h2>Parámetros</h2><p>${measured}/8 con lectura. Los cuatro prioritarios aparecen primero.</p></div><div class="param-grid">${state.data.parameters.map((p,i)=>`<button class="parameter-card ${i<4?'priority-param':''}" data-action="measurement"><div><small>${esc(p.name)}</small><strong>${p.latest?esc(p.latest.value):'—'}</strong><span>${esc(p.unit)}</span></div><p>Objetivo ${esc(p.target)} ${esc(p.unit)}</p></button>`).join('')}</div>${state.measurements.length?`<div class="section-title"><div><p>HISTORIAL</p><h2>Últimas lecturas</h2></div></div><div class="timeline">${[...state.measurements].reverse().slice(0,8).map(m=>{const p=state.data.parameters.find(x=>x.key===m.key);return `<div class="timeline-item"><strong>${esc(p?.name)} · ${esc(m.value)} ${esc(p?.unit)}</strong><small>${fmtDate(m.at)} ${m.note?'· '+esc(m.note):''}</small></div>`}).join('')}</div>`:''}`}
function equipmentView(){const groups=[['filtration','Filtración'],['flow','Movimiento'],['skimmer','Skimmer'],['lighting','Iluminación'],['topoff','Reposición'],['test','Medición']];return `<div class="page-intro"><p class="kicker">SISTEMAS</p><h2>Equipamiento</h2><p>Separado por función para localizar rápido qué funciona, qué está averiado y qué merece revisar.</p></div>${groups.map(([k,n])=>{const xs=state.data.equipment.filter(x=>x.category===k);return xs.length?`<div class="section-title"><div><p>${n.toUpperCase()}</p><h2>${n}</h2></div></div><div class="equipment-list">${xs.map(x=>equipmentRow(x)).join('')}</div>`:''}).join('')}`}
function equipmentRow(x){const bad=x.status==='broken',unknown=x.status==='unknown';return `<button class="equipment-row" data-entity-type="equipment" data-entity-id="${x.id}"><div class="equipment-icon">${iconFor(x.category)}</div><div><b>${esc(x.name)}</b><small>${esc(x.model||x.notes||'')}</small></div><span class="state-tag ${bad?'bad':unknown?'pending':'good'}">${bad?'Averiado':unknown?'Revisar':'OK'}</span></button>`}
function advisorView(){const missing=state.data.parameters.filter(p=>!p.latest).slice(0,4);return `<div class="page-intro"><p class="kicker">REEF ADVISOR</p><h2>Decisiones, no ruido</h2><p>La IA prioriza acciones y evita compras innecesarias.</p></div><article class="ai-hero"><span>DECISIÓN ACTUAL</span><h3>No comprar coral todavía</h3><p>Primero necesitamos la analítica Día 0 y cerrar temperatura, reposición y skimmer. Con peces adaptados desde hace años, los cambios deben ser graduales.</p><div><em>Confianza alta</em><em>Coste 0 € ahora</em></div></article><div class="section-title"><div><p>SIGUIENTE DESBLOQUEO</p><h2>Datos necesarios</h2></div></div><div class="advisor-steps">${missing.map((p,i)=>`<div><span>${i+1}</span><b>${esc(p.name)}</b><small>Registrar lectura</small></div>`).join('')}</div><div class="section-title"><div><p>AUTOMATIZACIÓN</p><h2>Programaciones detectadas</h2></div></div><div class="automation-grid"><article><span>NERO 5</span><strong>${esc(state.data.automation.nero5.mode)}</strong><p>Referencia observada ${esc(state.data.automation.nero5.referencePercent)}%</p></article><article><span>FLUVAL</span><strong>Programa activo</strong><p>Curva capturada; valores exactos pendientes de confirmar.</p></article></div>`}
function iconFor(c){return({filtration:'▤',flow:'≈',skimmer:'◌',lighting:'☀',topoff:'💧',test:'⌁'}[c]||'⚙')}
function bindDynamic(){main.querySelectorAll('[data-action="measurement"]').forEach(b=>b.onclick=()=>$('#measurementDialog').showModal());main.querySelectorAll('[data-action="maintenance"]').forEach(b=>b.onclick=()=>$('#maintenanceDialog').showModal());main.querySelectorAll('[data-entity-id]').forEach(b=>b.onclick=()=>showEntity(b.dataset.entityType,b.dataset.entityId));main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));}
function showEntity(type,id){const x=(type==='livestock'?state.data.livestock:state.data.equipment).find(v=>v.id===id);if(!x)return;const dlg=$('#entityDialog'),content=$('#entityDialogContent');if(type==='livestock'){const individuals=x.individuals?.map(i=>`<div class="individual-row"><span>${i.sex==='female'?'♀':'♂'}</span><div><b>${esc(i.label)}</b><small>${i.status==='alive'?'Vivo':'Estado pendiente'}</small></div></div>`).join('')||'';content.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">FICHA DE HABITANTE</p><h2>${esc(x.commonName)}</h2></div><button class="icon-btn" id="closeEntity">×</button></div><div class="profile-photo">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.commonName)}">`:`<span>🐟</span>`}</div><div class="profile-name"><h3>${esc(x.scientificName)}</h3><span>ID ${Math.round((x.confidence??1)*100)}%</span></div><div class="detail-grid"><div class="detail-stat"><small>Unidades</small><strong>${x.countIsEstimate?`${x.countMin}–${x.countMax}`:x.count}</strong></div><div class="detail-stat"><small>Tienda compra</small><strong>${esc(x.shop||'Pendiente')}</strong></div><div class="detail-stat"><small>Talla compra</small><strong>${esc(x.purchaseSize||'Pendiente')}</strong></div><div class="detail-stat"><small>Precio pagado</small><strong>${euro(x.purchasePrice)}</strong></div><div class="detail-stat"><small>Mercado actual</small><strong>${euro(x.marketPrice)}</strong></div><div class="detail-stat"><small>Fuente</small><strong>${esc(x.marketSource||'Pendiente')}</strong></div></div>${individuals?`<div class="section-title"><div><p>INDIVIDUOS</p><h2>Dentro de esta ficha</h2></div></div><div class="individuals">${individuals}</div>`:''}<article class="info-card"><b>Notas</b><p>${esc(x.notes||'Sin notas')}</p></article>`;}else{content.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">EQUIPAMIENTO</p><h2>${esc(x.name)}</h2></div><button class="icon-btn" id="closeEntity">×</button></div><div class="detail-grid"><div class="detail-stat"><small>Estado</small><strong>${esc(x.status)}</strong></div><div class="detail-stat"><small>Modelo</small><strong>${esc(x.model||'Confirmado')}</strong></div></div><article class="info-card"><b>Notas</b><p>${esc(x.notes||'Sin notas')}</p></article>`;}$('#closeEntity').onclick=()=>dlg.close();dlg.showModal();}
boot().catch(err=>{main.innerHTML=`<div class="empty">No se pudo cargar el inventario. ${esc(err.message)}</div>`});