const CANDIDATE_KEY='aq_candidate_lab_v1';
function candidateList(){try{return JSON.parse(localStorage.getItem(CANDIDATE_KEY)||'[]')}catch{return[]}}
function saveCandidates(xs){localStorage.setItem(CANDIDATE_KEY,JSON.stringify(xs))}
function currentParam(key){return state?.data?.parameters?.find(p=>p.key===key)?.latest?.value??null}
function inRange(v,min,max){return v!=null&&Number(v)>=min&&Number(v)<=max}
function detectCandidateType(q){const s=q.toLowerCase();if(/coral|euphy|torch|hammer|frog|caulast|zoa|montip|acrop|sps|lps|sarcophy|rhodact|discosoma|xenia/.test(s))return'coral';if(/pez|ocell|payaso|tang|ciruj|gob|blenn|wrasse|mandar|chromis|damisela|vulpin|foxface|firefish/.test(s))return'fish';if(/gamba|caracol|cangrejo|erizo|estrella|invertebr/.test(s))return'invertebrate';return'equipment'}
function coralProfile(s){if(/acrop|sps/.test(s))return{name:'SPS',light:'alta',flow:'alto y turbulento',zone:'alta',coords:[[0.2,.65,-.25],[-1,.55,-.3]],radius:15,hard:true};if(/euphy|torch|hammer|frog/.test(s))return{name:'Euphyllia',light:'media',flow:'moderado indirecto',zone:'media-baja',coords:[[.75,-.45,.1],[-.75,-.35,.15]],radius:18};if(/zoa/.test(s))return{name:'Zoanthus',light:'media-baja',flow:'moderado',zone:'baja-media',coords:[[-1.15,-.82,.15],[.95,-.78,.2]],radius:8};if(/caulast|hulk|candy/.test(s))return{name:'Caulastrea',light:'media',flow:'moderado indirecto',zone:'media-baja',coords:[[.35,-.72,.08],[-.95,-.62,.16]],radius:10};return{name:'Coral',light:'media',flow:'moderado',zone:'media',coords:[[.25,-.3,.1],[-.95,-.4,.15]],radius:12}}
function analyzeCandidate(query){const q=query.trim(),s=q.toLowerCase(),type=detectCandidateType(q),measured=state.data.parameters.filter(p=>p.latest).length;let verdict='CONDICIONAL',score=60,reasons=[],actions=[],placements=[];
 if(type==='coral'){const p=coralProfile(s),temp=currentParam('temperature'),sal=currentParam('salinity'),po4=currentParam('phosphate'),no3=currentParam('nitrate');placements=p.coords.map((c,i)=>({label:`Zona ${i+1} · ${p.zone}`,x:c[0],y:c[1],z:c[2],detail:`Luz ${p.light}; flujo ${p.flow}; separación orientativa ${p.radius} cm.`}));if(measured<4){score=35;reasons.push('Falta analítica Día 0: el coral queda bloqueado hasta disponer al menos de temperatura, salinidad, PO₄ y NO₃.')}else{if(inRange(temp,24,26)&&inRange(sal,34,35.5)&&inRange(po4,.02,.12)&&inRange(no3,1,15)){verdict='APTO CON ACLIMATACIÓN';score=p.hard?68:86;reasons.push('Los parámetros básicos registrados están dentro del rango operativo de la app.')}else{score=42;reasons.push('Alguno de los parámetros básicos está fuera del rango objetivo actual; estabilizar antes de introducirlo.')}}if(p.hard){verdict='NO AHORA';score=Math.min(score,45);reasons.push('SPS exige más estabilidad, madurez, luz y control fino de KH/Ca/Mg que el sistema todavía no ha demostrado.')}actions.push('Confirmar especie/variedad exacta y tamaño del frag.','Revisar agresividad y distancia respecto a otros corales.','Ajustar colocación final según respuesta real durante 7–14 días.');}
 if(type==='fish'){const current=state.data.livestock.filter(x=>x.kind==='fish'&&x.status==='alive').reduce((a,x)=>a+(x.count||1),0);if(/tang|ciruj|vulpin|foxface|siganus/.test(s)){verdict='NO RECOMENDADO';score=15;reasons.push('El tamaño adulto y la necesidad de nado no son adecuados para un sistema de 123 L.');}else if(/mandar/.test(s)){verdict='NO AHORA';score=28;reasons.push('Requiere disponibilidad alimentaria/microfauna estable que debe demostrarse antes.');}else{score=current>=4?55:72;reasons.push(`Carga actual registrada: ${current} peces. Compatibilidad conductual y tamaño adulto deben comprobarse para la especie exacta.`)}placements=[{label:'Volumen de nado central',x:.15,y:.15,z:.15,detail:'Los peces no tienen una posición fija; el gemelo representa espacio de nado y refugios.'}];actions.push('Confirmar especie científica y talla de compra.','Revisar agresividad con la pareja de Ocellaris existente.','No introducir dos peces nuevos simultáneamente.');}
 if(type==='invertebrate'){score=70;reasons.push('La necesidad debe justificarse por función real: algas, detrito o biodiversidad; no añadir un pack genérico por rutina.');placements=[{label:'Sustrato / roca baja',x:1.25,y:-1.15,z:.35,detail:'Ubicación visual orientativa; el animal se moverá libremente.'}];actions.push('Confirmar especie exacta y compatibilidad con peces/corales.','Dimensionar unidades según necesidad real observada.');}
 if(type==='equipment'){let category=/ventil|cool|chiller|frio|temper/.test(s)?'temperature':/luz|led|fluval/.test(s)?'lighting':/bomba|nero|tunze|flujo/.test(s)?'flow':/ato|relleno|repos/.test(s)?'topoff':/skimmer/.test(s)?'skimmer':'other';const owned=state.data.equipment.filter(e=>e.category===category);if(owned.length){score=48;reasons.push(`Ya existe equipamiento de la misma función: ${owned.map(x=>x.name).join(', ')}. Primero debe justificarse sustitución o redundancia.`)}else{score=75;reasons.push('No se detecta un equipo equivalente registrado; falta validar medidas, consumo, instalación y coste total.')}if(category==='temperature')placements=[{label:'Borde superior / superficie',x:1.9,y:1.55,z:0,detail:'Orientar refrigeración a la superficie, manteniendo electricidad protegida de salpicaduras.'},{label:'Lateral superior alternativo',x:-1.9,y:1.5,z:0,detail:'Alternativa según tapa, cableado y acceso.'}];else if(category==='flow')placements=[{label:'Lateral derecho alto',x:2.35,y:.35,z:0,detail:'Orientación cruzada hacia la roca evitando chorro directo sobre coral.'},{label:'Lateral izquierdo medio',x:-2.35,y:.1,z:0,detail:'Alternativa para eliminar zonas muertas.'}];else if(category==='lighting')placements=[{label:'Eje superior de la urna',x:0,y:1.7,z:0,detail:'Centrar distribución PAR y reducir acumulación térmica bajo tapa cuando sea posible.'}];else placements=[{label:'Instalación técnica',x:2.2,y:-.2,z:-.7,detail:'Posición aproximada; Instalaciones debe validar acceso, cableado y seguridad.'}];actions.push('Comprobar medidas y compatibilidad física.','Comparar 2–3 alternativas con precio total a 41020.','No comprar hasta que Finanzas y el especialista técnico lo autoricen.');}
 return{id:'cand-'+Date.now(),query:q,type,verdict,score,reasons,actions,placements,createdAt:new Date().toISOString()}}
function candidateCard(c){const tone=c.score>=75?'ok':c.score>=45?'warn':'bad';return `<article class="candidate-card ${tone}"><div class="candidate-top"><div><small>${esc(c.type.toUpperCase())}</small><h4>${esc(c.query)}</h4></div><strong>${c.score}/100</strong></div><div class="candidate-verdict">${esc(c.verdict)}</div>${c.reasons.map(r=>`<p>${esc(r)}</p>`).join('')}<div class="candidate-places">${c.placements.map((p,i)=>`<button data-cand-place="${c.id}" data-place="${i}"><b>${esc(p.label)}</b><small>${esc(p.detail)}</small><span>Ver en Gemelo ›</span></button>`).join('')}</div><details><summary>Pasos antes de decidir</summary>${c.actions.map((a,i)=>`<div class="candidate-step"><span>${i+1}</span>${esc(a)}</div>`).join('')}</details><button class="candidate-remove" data-cand-remove="${c.id}">Eliminar simulación</button></article>`}
function candidateLabBlock(){const xs=candidateList();return `<section class="candidate-lab"><small>LABORATORIO DE CANDIDATOS</small><h3>¿Puedo meter esto en mi acuario?</h3><p>Escribe cualquier coral, pez, invertebrado o equipo. Acuario AI lo cruza con tu urna, habitantes, parámetros, equipo y presupuesto y te propone lugares concretos en el Gemelo 3D.</p><form id="candidateForm"><input id="candidateInput" placeholder="Ej.: Euphyllia torch, Gobio, ventilador…" autocomplete="off"><button type="submit">Analizar</button></form>${xs.length?`<div class="candidate-results">${xs.slice().reverse().map(candidateCard).join('')}</div>`:'<div class="candidate-empty">Todavía no has probado ningún candidato.</div>'}</section>`}
function injectCandidatesToTwin(){if(typeof twinPlacements==='undefined')return;const ids=new Set(twinPlacements.map(x=>x.id));candidateList().forEach(c=>{if(c.score<45)return;c.placements.forEach((p,i)=>{const id=`${c.id}-${i}`;if(ids.has(id))return;twinPlacements.push({id,kind:c.type==='equipment'?'equipment':c.type,state:'proposal',name:c.query,x:p.x,y:p.y,z:p.z,candidateId:c.id});ids.add(id)})})}
injectCandidatesToTwin();
const advisorBeforeCandidates=advisorView;advisorView=function(){return advisorBeforeCandidates()+candidateLabBlock()};
const twinBeforeCandidates=virtualReefView;virtualReefView=function(){return twinBeforeCandidates()+`<section class="twin-card candidate-twin-help"><small>PRUEBA CUALQUIER COSA</small><h3>Simula antes de comprar</h3><p>Introduce el candidato desde IA. Si supera el filtro mínimo, aparecerá automáticamente en este Gemelo con una o varias posiciones propuestas.</p><button data-go="advisor" class="primary compact">Analizar candidato</button></section>`};
document.addEventListener('submit',e=>{if(e.target?.id!=='candidateForm')return;e.preventDefault();const input=document.querySelector('#candidateInput'),q=input?.value.trim();if(!q)return;const xs=candidateList();xs.push(analyzeCandidate(q));saveCandidates(xs.slice(-20));injectCandidatesToTwin();render();setTimeout(()=>document.querySelector('.candidate-results')?.scrollIntoView({behavior:'smooth',block:'start'}),30)});
document.addEventListener('click',e=>{const rm=e.target.closest?.('[data-cand-remove]');if(rm){saveCandidates(candidateList().filter(x=>x.id!==rm.dataset.candRemove));render();return}const b=e.target.closest?.('[data-cand-place]');if(b){const c=candidateList().find(x=>x.id===b.dataset.candPlace),p=c?.placements?.[Number(b.dataset.place)];if(!c||!p)return;state.view='twin';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='twin'));localStorage.setItem(twinModeKey,'all');render();setTimeout(()=>{const msg=document.createElement('div');msg.className='twin-toast';msg.textContent=`${c.query}: ${p.label}`;document.querySelector('#reef3d')?.appendChild(msg);setTimeout(()=>msg.remove(),3200)},500)}});