const commerceCatalog={
 'light-fluval':{replacement:'Fluval Marine 3.0 LED para Flex Marine 123 L · ref. 14513',checked:'2026-08-12',offers:[{shop:'Comparador Idealo España',price:187.15,shipping:0,total:187.15,note:'Oferta indexada con envío incluido; confirmar stock/plazo antes de pagar.',url:'https://www.idealo.es/precios/203735593/fluval-marine-3-0-led-46w-75cm-14513.html'}],consumables:[],advice:'Si la pantalla actual falla, buscar primero la referencia exacta 14513. No sustituirla preventivamente.'},
 'skimmer-tunze':{replacement:'Tunze Comline DOC Skimmer 9004 · 9004.000',checked:'2026-08-12',offers:[{shop:'Tunze oficial',price:199.99,shipping:null,total:null,note:'Precio antes de IVA/envío según ficha; calcular entrega a 41020 en checkout.',url:'https://tunze.com/es/Comline-DOC-Skimmer-9004/9004.000'}],consumables:[{name:'Comline Foamer / bomba 9004.040',price:54.99,url:'https://tunze.com/es/Comline-Foamer/9004.040'},{name:'Unidad propulsora 9004.047',price:18.99,url:'https://tunze.com/es/Comline-Foamer/9004.040'}],advice:'Antes de comprar un skimmer completo, diagnosticar el actual: el recambio de bomba/rotor puede ser mucho más económico.'},
 'filter-eheim':{replacement:'EHEIM professionel 4+ 250 · 2271020',checked:'2026-08-12',offers:[],consumables:[{name:'Prefiltro 7428970',price:17.35,url:'https://eheim.com/es_ES/recambios/technik/aussenfilter/professionel-4/'},{name:'Cesta material filtrante 7429710',price:8.95,url:'https://eheim.com/es_ES/recambios/technik/aussenfilter/professionel-4/'},{name:'Flauta salida 7334528',price:9.91,url:'https://eheim.com/es_ES/recambios/technik/aussenfilter/professionel-4/'},{name:'Adaptador seguridad 7428718',price:24.88,url:'https://eheim.com/es_ES/recambios/'}],advice:'No cambiar el filtro completo por desgaste normal. EHEIM mantiene un catálogo amplio de recambios para este modelo.'},
 'phosphate-hanna':{replacement:'Hanna Checker HI774',checked:'2026-08-12',offers:[],consumables:[{name:'Reactivos fosfato ULR HI774-25 · 25 tests',price:15,vatExcluded:true,url:'https://www.hannainst.es/parametros/5504-reactivo-fosfatos-rango-ultra-bajo-000-a-090-ppm-para-agua-marina-25-test.html'}],advice:'Comprar reactivo solo cuando queden pocas mediciones y revisar caducidad del lote actual.'},
 'nitrate-hanna':{replacement:'Hanna Checker HI782',checked:'2026-08-12',offers:[],consumables:[{name:'Reactivos nitrato HR HI782-25 · 25 tests',price:21,vatExcluded:true,url:'https://www.hannainst.es/productos/6142-reactivo-para-25-test-nitratos-rango-alto-para-agua-marina.html'}],advice:'El consumible correcto es HI782-25. No comprar otro checker mientras el actual funcione.'},
 'salinity-hanna':{replacement:'Hanna HI98319 Marine Salinity Tester',checked:'2026-08-12',offers:[],consumables:[{name:'Solución de calibración 35 ppt',price:null,url:'https://www.hannainst.es/'}],advice:'Priorizar solución de calibración; el medidor no necesita reemplazo mientras calibre y mida correctamente.'},
 'flow-nero5':{replacement:'AquaIllumination Nero 5',checked:'2026-08-12',offers:[],consumables:[],advice:'No comprar repuesto preventivo. Mantener y limpiar; comparar bomba completa/controlador/fuente solo si aparece una avería concreta.'}
};
function money(v){return v==null?'Por calcular':new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v)}
function commerceBlock(id){const c=commerceCatalog[id];if(!c)return `<section class="buy-panel"><div class="buy-head"><div><small>COMPRA Y RECAMBIOS</small><h4>Pendiente de identificar</h4></div></div><p>Cuando confirmemos el modelo exacto, Acuario AI añadirá repuestos, fungibles y comparación de coste entregado.</p></section>`;const offers=[...(c.offers||[])].sort((a,b)=>(a.total??1e9)-(b.total??1e9));return `<section class="buy-panel"><div class="buy-head"><div><small>COMPRA Y RECAMBIOS · CP 41020</small><h4>${esc(c.replacement)}</h4></div><span>${c.checked}</span></div><p>${esc(c.advice)}</p>${offers.length?`<div class="offer-list">${offers.map((o,i)=>`<a class="offer-row ${i===0?'best':''}" href="${o.url}" target="_blank" rel="noopener"><div><b>${i===0?'★ Mejor oferta verificada':'Oferta'} · ${esc(o.shop)}</b><small>${esc(o.note)}</small></div><strong>${money(o.total??o.price)}</strong></a>`).join('')}</div>`:`<div class="price-pending">Comparación de tiendas pendiente de una oferta verificable con precio total.</div>`}${c.consumables?.length?`<div class="consumables"><small>FUNGIBLES / RECAMBIOS COMPATIBLES</small>${c.consumables.map(x=>`<a href="${x.url}" target="_blank" rel="noopener"><span>${esc(x.name)}</span><b>${money(x.price)}${x.vatExcluded?' + IVA':''}</b></a>`).join('')}</div>`:''}<footer>El ganador solo se marca cuando conocemos precio total. Si una tienda no publica portes a 41020, la app no inventa el coste: queda “por calcular”.</footer></section>`}
const equipmentViewCommerce=equipmentView;equipmentView=function(){const html=equipmentViewCommerce();setTimeout(()=>{document.querySelectorAll('.equip-detail').forEach(d=>{const btn=d.querySelector('[data-entity-id]');if(!btn)return;const id=btn.dataset.entityId;const section=d.querySelector('section');if(section&&!section.querySelector('.buy-panel'))section.insertAdjacentHTML('beforeend',commerceBlock(id));});},0);return html};
