const reefDepartments=[['Dirección Reef','Integra prioridades y bloquea cambios simultáneos'],['Química','Salinidad, KH, NO₃, PO₄, pH, Mg'],['Peces','Compatibilidad, carga y conducta'],['Corales','Blandos, LPS y SPS por separado'],['Temperatura','Verano, control y seguridad térmica'],['Iluminación','Fluval Marine 3.0 y fotoperiodo'],['Movimiento','Nero 5 y distribución de flujo'],['Filtración','EHEIM y skimmer'],['Instalaciones','Montaje y puesta en marcha guiada'],['Compras','Precio, enlace y coste total'],['Finanzas','Optimiza presupuesto y reserva'],['Mantenimiento','Tareas y comprobación posterior']];
const currentPriorities=[
 {p:1,title:'Analítica Día 0',owner:'Química',cost:0,detail:'Registrar temperatura, salinidad, PO₄ y NO₃. Añadir KH si el test está operativo. Hasta entonces no comprar coral ni dosificar.'},
 {p:2,title:'Verificar control térmico',owner:'Temperatura',cost:0,detail:'Confirmar si la salida COOL del Aqua Medic T controller twin realmente ha fallado. No abrir el aparato.'},
 {p:3,title:'Limpieza gradual del fondo',owner:'Mantenimiento',cost:0,detail:'Usar el EHEIM Quick Vac pro solo en una zona pequeña y registrar qué sector se ha limpiado.'},
 {p:4,title:'Diagnóstico del Tunze',owner:'Filtración',cost:0,detail:'Confirmar modelo/etiqueta y revisar obstrucción, rotor y toma de aire sin comprar skimmer completo todavía.'},
 {p:5,title:'Recuperar reposición automática',owner:'Instalaciones',cost:0,detail:'Diagnosticar el D-D H2Ocean Compact ATO antes de sustituirlo.'}
];
const purchaseCandidates=[
 {name:'Aqua Medic T controller twin 2.0',price:58.20,shipping:0,total:58.20,condition:'Solo si confirmas que la salida COOL actual está averiada.',shop:'Cetamar · recogida presencial',url:'https://www.cetamar.com/es/controladores-de-temperatura/6774-t-controller-twin-20-aqua-medic.html'},
 {name:'Hobby Aqua Cooler V4',price:47.75,shipping:0,total:47.75,condition:'Solo si las mediciones muestran sobretemperatura real tras recuperar un controlador fiable.',shop:'Cetamar · recogida presencial',url:'https://www.cetamar.com/es/hobby-ventiladores/2330-ventilador-aqua-cooler-v4-hobby.html'},
 {name:'Aquaforest Perfect Water 20 L',price:35,shipping:0,total:35,condition:'Solo cuando el Director Reef ordene un cambio de agua; alternativa preparada económica en Cetamar.',shop:'Cetamar · recogida presencial',url:'https://www.cetamar.com/es/39-sal'},
 {name:'Natural Seawater 20 L',price:41.66,shipping:0,total:41.66,condition:'Alternativa de agua de mar preparada; usar solo si el cambio está indicado.',shop:'Cetamar · recogida presencial',url:'https://www.cetamar.com/es/403-natural-seawater'},
 {name:'Red Sea Coral Pro Salt 7 kg',price:36,shipping:0,total:36,condition:'Solo si vuelves a preparar agua en casa con agua base adecuada; no usar con agua de grifo.',shop:'Cetamar · recogida presencial',url:'https://www.cetamar.com/es/39-sal'}
];
function savedBudget(){const v=Number(localStorage.getItem('aq_budget')||'100');return Number.isFinite(v)&&v>=0?v:100}
function financePlan(amount){let left=amount;const plan=[];const controller=purchaseCandidates[0];if(left>=controller.total){plan.push({...controller,kind:'condicional'});left-=controller.total}return{amount,left,plan}}
function moneyDirector(v){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v)}
function directorPriorities(){return `<section class="director-card"><small>ORDEN DE TRABAJO</small><h3>Prioridades actuales</h3><div class="priority-list">${currentPriorities.map(x=>`<div class="priority-task"><span>${x.p}</span><div><b>${x.title}</b><small>${x.owner} · ${x.detail}</small></div><em>${x.cost===0?'0 €':moneyDirector(x.cost)}</em></div>`).join('')}</div></section>`}
function financialDirector(){const b=savedBudget(),plan=financePlan(b);return `<section class="director-card" id="financeDirector"><small>DIRECTOR FINANCIERO REEF</small><h3>Presupuesto disponible</h3><p>Introduce cuánto quieres gastar. El sistema no fuerza a gastar el total y mantiene compras condicionadas hasta que el especialista correspondiente las autorice.</p><div class="finance-box"><input id="reefBudgetInput" inputmode="decimal" type="number" min="0" step="1" value="${b}" aria-label="Presupuesto disponible en euros"><button id="reefBudgetApply" type="button">Calcular</button></div><div class="finance-summary"><b>Plan con ${moneyDirector(b)}</b><br>${plan.plan.length?`Reserva ${moneyDirector(plan.left)} después de la compra prioritaria condicional.`:`No hay presupuesto suficiente para la primera compra condicional; las tareas de coste 0 siguen activas.`}</div><div class="finance-items">${plan.plan.map(x=>`<article class="finance-item"><div class="row"><b>${x.name}</b><strong>${moneyDirector(x.total)}</strong></div><small>${x.shop} · portes ${moneyDirector(x.shipping)} · total ${moneyDirector(x.total)}. ${x.condition}</small><a href="${x.url}" target="_blank" rel="noopener">Abrir producto</a></article>`).join('')}</div><div class="blocked-note">No comprar el ventilador, agua, sal ni dosificar productos solo porque quede presupuesto. La IA exige primero el dato que desbloquea cada gasto.</div></section>`}
function waterDirector(){return `<section class="director-card"><small>AGUA · COMPRA DETALLADA</small><h3>Opciones si se ordena un cambio de 20 L</h3><p>Como recoges en Cetamar, la app contabiliza portes 0 €. Estas opciones quedan bloqueadas hasta tener la analítica actual.</p><div class="water-options">${purchaseCandidates.slice(2).map(x=>`<a class="water-option" href="${x.url}" target="_blank" rel="noopener"><div><b>${x.name}</b><small>${x.shop} · envío/recogida 0 € · ${x.condition}</small></div><strong>${moneyDirector(x.total)}</strong></a>`).join('')}</div><div class="blocked-note">Entre las dos aguas ya preparadas, Perfect Water 20 L aparece actualmente más barata que Natural Seawater 20 L. La elección final dependerá de la analítica y del objetivo del cambio.</div></section>`}
function departmentsDirector(){return `<section class="director-card"><small>PERSONAL ESPECÍFICO</small><h3>12 departamentos coordinados</h3><div class="dept-grid">${reefDepartments.map(d=>`<div class="dept-pill"><b>${d[0]}</b><small>${d[1]}</small></div>`).join('')}</div></section>`}
const oldAdvisorDirector=advisorView;advisorView=function(){return `<div class="page-intro"><p class="kicker">REEF COMMAND</p><h2>Director Reef</h2><p>Un único orden de prioridades coordinado por especialistas, compras e impacto presupuestario.</p><span class="version-chip">v1.0 · recuperación</span></div><div class="director-shell">${directorPriorities()}${financialDirector()}${waterDirector()}${departmentsDirector()}${oldAdvisorDirector()}</div>`};
const oldHomeDirector=homeView;homeView=function(){return oldHomeDirector().replace('Reef 130','Flex Marine 123').replace('Sevilla · Marino · activo desde ~2023','Sevilla · Fluval Flex Marine 123 L · iniciado 2022')};
if(typeof installationGuides!=='undefined'&&installationGuides['doser-aquamedic-evo']){installationGuides['doser-aquamedic-evo'].name='Aqua Medic Reefdoser EVO 5';installationGuides['doser-aquamedic-evo'].status='Confirmado · sin estrenar';installationGuides['doser-aquamedic-evo'].summary='Dosificador Aqua Medic Reefdoser EVO 5 confirmado por pedido histórico. Cinco canales, comprado y nunca instalado.';installationGuides['doser-aquamedic-evo'].steps[0]=['Modelo confirmado','Reefdoser EVO 5. No hace falta volver a identificarlo; el siguiente paso será una instalación en seco y calibración con agua.']}
if(typeof ensureInstallInventory==='function'){ensureInstallInventory=function(){if(!state?.data?.equipment)return;if(typeof equipmentKnowledge!=='undefined'){const e=state.data.equipment.find(x=>x.id==='doser-aquamedic-evo5');if(e)equipmentKnowledge[e.id]={title:'Dosificación automática de 5 canales',desc:'Aqua Medic Reefdoser EVO 5 confirmado.',specs:['5 canales','control por app','calibración por canal'],capabilities:['automatizar dosis medidas','repartir dosis diarias','mantener consumos estables cuando exista coral'],recommend:'No activar todavía. Primero analítica, consumo real y calibración con agua.',source:'pedido histórico + Aqua Medic'};}}}
document.addEventListener('click',e=>{if(e.target?.id==='reefBudgetApply'){const v=Math.max(0,Number(document.querySelector('#reefBudgetInput')?.value||0));localStorage.setItem('aq_budget',String(v));render();setTimeout(()=>document.querySelector('#financeDirector')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}});