const aqPhotos=JSON.parse(localStorage.getItem('aq_photos')||'{}');
const aqEvents=JSON.parse(localStorage.getItem('aq_life_events')||'[]');
const originalHomeView=homeView,originalLivestockMini=livestockMini,originalLivestockCard=livestockCard,originalShowEntity=showEntity;
function ownPhoto(id,fallback){return aqPhotos[id]||fallback||null}
function saveEvents(){localStorage.setItem('aq_life_events',JSON.stringify(aqEvents))}
function photoMarkup(x,cls){const src=ownPhoto(x.id,x.image);return src?`<img src="${src}" alt="${esc(x.commonName||x.name)}">`:`<div class="placeholder-fish">${x.kind==='invertebrate'?'🐌':'🐟'}</div>`}
function livestockMini(x){const src=ownPhoto(x.id,x.image);return `<button class="mini-fish" data-entity-type="livestock" data-entity-id="${x.id}"><div class="mini-photo">${src?`<img src="${src}" alt="${esc(x.commonName)}">`:`<span>${x.kind==='invertebrate'?'🐌':'🐟'}</span>`}<em>${x.countIsEstimate?`${x.countMin}–${x.countMax}`:`×${x.count}`}</em></div><b>${esc(x.commonName)}</b><small>${esc(x.scientificName)}</small></button>`}
function livestockCard(x){const sex=x.individuals?.map(i=>i.label).join(' + '),src=ownPhoto(x.id,x.image);return `<button class="life-card" data-entity-type="livestock" data-entity-id="${x.id}"><div class="life-photo">${src?`<img src="${src}" alt="${esc(x.commonName)}">`:`<div class="placeholder-fish">${x.kind==='invertebrate'?'🐌':'🐟'}</div>`}<span class="count-badge">${x.countIsEstimate?`${x.countMin}–${x.countMax}`:`${x.count} ud.`}</span>${aqPhotos[x.id]?'<span class="own-photo-badge">FOTO TUYA</span>':''}</div><div class="life-body"><div class="life-title"><div><h3>${esc(x.commonName)}</h3><p>${esc(x.scientificName)}</p></div><span>›</span></div>${sex?`<div class="micro-pill">${esc(sex)}</div>`:''}<div class="life-meta"><span>${esc(x.shop||'Tienda pendiente')}</span><span>${x.purchaseSize?`Talla compra ${esc(x.purchaseSize)}`:'Talla pendiente'}</span></div></div></button>`}
function homeView(){const base=originalHomeView();const recent=[...aqEvents].reverse().slice(0,4);return base+`<div class="section-title"><div><p>DIARIO VITAL</p><h2>Últimos cambios</h2></div><button class="text-btn" id="quickLifeEvent">Añadir</button></div>${recent.length?`<div class="life-timeline">${recent.map(e=>`<div class="life-event ${e.type}"><span>${e.type==='death'?'✕':e.type==='arrival'?'+':'•'}</span><div><b>${esc(e.title)}</b><small>${fmtDate(e.at)}${e.note?' · '+esc(e.note):''}</small></div></div>`).join('')}</div>`:`<article class="info-card"><b>Sin eventos registrados todavía</b><p>Aquí quedarán nuevas incorporaciones, muertes, cambios de sexo/pareja y observaciones importantes.</p></article>`}`}
function bindDynamic(){main.querySelectorAll('[data-action="measurement"]').forEach(b=>b.onclick=()=>$('#measurementDialog').showModal());main.querySelectorAll('[data-action="maintenance"]').forEach(b=>b.onclick=()=>$('#maintenanceDialog').showModal());main.querySelectorAll('[data-entity-id]').forEach(b=>b.onclick=()=>showEntity(b.dataset.entityType,b.dataset.entityId));main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));const q=$('#quickLifeEvent');if(q)q.onclick=()=>addLifeEvent();}
function addLifeEvent(x){const label=x?.commonName||'Habitante';const type=prompt('Tipo de evento: escribe llegada, muerte u observación','observación');if(!type)return;const map={llegada:'arrival',muerte:'death','observación':'note',observacion:'note'};const normalized=map[type.toLowerCase()]||'note';const note=prompt('Detalle del evento (opcional)','')||'';aqEvents.push({type:normalized,title:`${label}: ${type}`,entityId:x?.id||null,note,at:new Date().toISOString()});saveEvents();render();}
async function choosePhoto(x){const input=document.createElement('input');input.type='file';input.accept='image/*';input.capture='environment';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const img=new Image();img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);try{aqPhotos[x.id]=canvas.toDataURL('image/jpeg',.78);localStorage.setItem('aq_photos',JSON.stringify(aqPhotos));showEntity('livestock',x.id);render();}catch(e){alert('No se pudo guardar la foto. Prueba con una imagen más pequeña.')}};img.src=URL.createObjectURL(file)};input.click()}
function showEntity(type,id){const x=(type==='livestock'?state.data.livestock:state.data.equipment).find(v=>v.id===id);if(!x)return;if(type!=='livestock'){originalShowEntity(type,id);return}const dlg=$('#entityDialog'),content=$('#entityDialogContent'),src=ownPhoto(x.id,x.image),individuals=x.individuals?.map(i=>`<div class="individual-row"><span>${i.sex==='female'?'♀':'♂'}</span><div><b>${esc(i.label)}</b><small>${i.status==='alive'?'Vivo':'Estado pendiente'}</small></div></div>`).join('')||'';content.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">FICHA DE HABITANTE</p><h2>${esc(x.commonName)}</h2></div><button class="icon-btn" id="closeEntity">×</button></div><div class="profile-photo">${src?`<img src="${src}" alt="${esc(x.commonName)}">`:'<span>🐟</span>'}</div><div class="profile-actions"><button class="action secondary-action" id="photoEntity">📷 ${aqPhotos[x.id]?'Cambiar foto':'Añadir mi foto'}</button><button class="action secondary-action" id="eventEntity">＋ Evento</button></div><div class="profile-name"><h3>${esc(x.scientificName)}</h3><span>ID ${Math.round((x.confidence??1)*100)}%</span></div><div class="detail-grid"><div class="detail-stat"><small>Unidades</small><strong>${x.countIsEstimate?`${x.countMin}–${x.countMax}`:x.count}</strong></div><div class="detail-stat"><small>Tienda compra</small><strong>${esc(x.shop||'Pendiente')}</strong></div><div class="detail-stat"><small>Talla compra</small><strong>${esc(x.purchaseSize||'Pendiente')}</strong></div><div class="detail-stat"><small>Precio pagado</small><strong>${euro(x.purchasePrice)}</strong></div><div class="detail-stat"><small>Mercado actual</small><strong>${euro(x.marketPrice)}</strong></div><div class="detail-stat"><small>Fuente</small><strong>${esc(x.marketSource||'Pendiente')}</strong></div></div>${individuals?`<div class="section-title"><div><p>INDIVIDUOS</p><h2>Dentro de esta ficha</h2></div></div><div class="individuals">${individuals}</div>`:''}<article class="info-card"><b>Historial de esta ficha</b><p>${aqEvents.filter(e=>e.entityId===x.id).length} eventos registrados. Las fotos y eventos se guardan en este iPhone.</p></article><article class="info-card"><b>Notas</b><p>${esc(x.notes||'Sin notas')}</p></article>`;$('#closeEntity').onclick=()=>dlg.close();$('#photoEntity').onclick=()=>choosePhoto(x);$('#eventEntity').onclick=()=>addLifeEvent(x);dlg.showModal()}
