const reefExperts=[['fish','🐠','Peces'],['soft','🌿','Corales blandos'],['lps','🪸','Corales LPS'],['sps','◆','Corales SPS'],['water','💧','Química del agua'],['flow','≈','Movimiento'],['light','☀','Iluminación'],['thermal','🌡','Temperatura'],['filtration','▤','Filtración'],['equipment','⚙','Equipamiento'],['health','✚','Salud animal'],['ops','✓','Mantenimiento']];
const expertAdvice={
 fish:{verdict:'No añadir peces',why:'Los actuales llevan años adaptados. Antes de ampliar población hay que estabilizar temperatura, agua de reposición y revisar compatibilidad/espacio.',needs:['temperatura máxima diaria','salinidad','NO₃','PO₄'],authority:'bloquea nuevas compras de peces si faltan datos o hay incompatibilidad'},
 soft:{verdict:'Primer grupo coral futuro',why:'Los blandos son la vía más tolerante para reintroducir coral cuando el sistema tenga varias semanas estable.',needs:['temperatura estable','salinidad estable','NO₃','PO₄'],authority:'autoriza el primer coral de prueba'},
 lps:{verdict:'Aún no comprar',why:'Necesitan estabilidad de alcalinidad, nutrientes, temperatura y flujo más controlado que el estado actual.',needs:['KH','temperatura','salinidad','NO₃','PO₄'],authority:'define especie, zona, flujo y aclimatación LPS'},
 sps:{verdict:'Bloqueado',why:'No recomendar SPS sin estabilidad prolongada, KH consistente y medición PAR real.',needs:['KH histórico','PAR','Ca','Mg','temperatura'],authority:'puede vetar SPS aunque otros especialistas aprueben'},
 water:{verdict:'Analítica Día 0',why:'Registrar temperatura, salinidad, PO₄ y NO₃ antes de modificar iluminación, dosificar o comprar.',needs:['temperatura','salinidad','PO₄','NO₃'],authority:'valida cualquier decisión química'},
 flow:{verdict:'Nero 5 como bomba principal',why:'En 130 L la Nero 5 tiene margen de sobra. Las otras dos bombas no deben sumar caudal hasta identificarlas y observar zonas muertas.',needs:['posición de bombas','vídeo de movimiento','corales presentes'],authority:'define modo y porcentajes de circulación'},
 light:{verdict:'Perfil de recuperación',why:'La pantalla está dentro de la tapa, hay historial de calor y actualmente no hay coral. Prioridad: reducir carga térmica y algas.',needs:['modelo exacto/watios','temperatura pico','futuros corales'],authority:'define ciclo y aclimatación lumínica'},
 thermal:{verdict:'Prioridad verano',why:'La sobretemperatura es uno de los riesgos más claros para volver a mantener coral.',needs:['máxima diaria','mínima nocturna','horas >26 ºC'],authority:'puede reducir luz y bloquear coral'},
 filtration:{verdict:'Recuperar skimmer, mantener EHEIM',why:'El EHEIM cubre bien el volumen. El Tunze debe diagnosticarse antes de sustituirlo.',needs:['estado rotor/venturi','frecuencia limpieza EHEIM'],authority:'define limpieza y medios filtrantes'},
 equipment:{verdict:'Comprar solo con evidencia',why:'Antes de recomendar una compra compara lo que ya tienes, necesidad real, compatibilidad, tamaño y precio.',needs:['inventario completo','medidas del hueco','presupuesto'],authority:'aprueba o veta compras'},
 health:{verdict:'Observar conducta',why:'Apetito, respiración, lesiones y cambios de conducta deben quedar registrados por ejemplar.',needs:['fotos','observaciones'],authority:'prioriza bienestar sobre estética'},
 ops:{verdict:'Rutina mínima y sostenible',why:'Cambios pequeños, limpieza por zonas y registro. Nada de rehacer el acuario de golpe.',needs:['último cambio de agua','última limpieza filtro'],authority:'convierte decisiones en tareas concretas'}
};
const neroProfile=[['00:00–08:30','Random','18%'],['08:30–10:30','Random','22%'],['10:30–19:30','Random','30%'],['19:30–22:00','Random','24%'],['22:00–00:00','Random','18%']];
const lightProfile=[['11:30','0','0','0','0','0'],['12:00','15','30','35','0','0'],['13:00','40','60','65','8','3'],['18:00','40','60','65','8','3'],['19:00','20','30','35','3','0'],['19:30','0','0','0','0','0']];
const equipmentKnowledge={
 'filter-eheim':{title:'Filtro externo principal',desc:'EHEIM professionel 4+ 250. Filtración mecánica y biológica con prefiltro extraíble, autocebado y función Xtender.',specs:['120–250 L','~950 L/h','6,1 L de recipiente','3,5 L de volumen filtrante','12 W'],capabilities:['retener detrito grueso en prefiltro','alojar material biológico','usar medios químicos de forma puntual','regular caudal','ganar unos días de margen con Xtender'],recommend:'Mantenerlo como filtración principal. Limpiar prefiltro y esponjas de forma escalonada; no lavar todo el material biológico a la vez ni usar Xtender como sustituto del mantenimiento.',source:'EHEIM · ficha oficial'},
 'flow-nero5':{title:'Bomba de movimiento principal',desc:'AquaIllumination Nero 5. Bomba de flujo amplio, orientable y programable.',specs:['hasta 11.356 L/h','30 W máx.','Random / Constant / Pulse / Feed','programación diaria'],capabilities:['crear flujo aleatorio','crear pulso','mantener caudal constante','modo alimentación','programar múltiples tramos diarios'],recommend:'Para este 130 L: Random 18–30% según horario. La captura actual al 30% constante es razonable como máximo diurno, pero prefiero noche reducida. Feed al mínimo durante la alimentación. No sumar las otras bombas hasta identificarlas.',source:'AquaIllumination · documentación oficial'},
 'skimmer-tunze':{title:'Skimmer interno',desc:'Probable Tunze Comline DOC Skimmer 9004; el modelo debe confirmarse por etiqueta.',specs:['si es 9004: 60–250 L','~150 L/h de aire','4 W','vaso 0,2 L','inmersión 225–245 mm'],capabilities:['exportar orgánicos por espuma','mejorar intercambio gaseoso','aspirar película superficial','funcionar sin sump'],recommend:'No comprar sustituto todavía. Desmontar y revisar venturi, tubo de aire, rotor/foamer y obstrucciones. Si confirmamos 9004, su dimensionado es adecuado para 130 L.',source:'Tunze · ficha oficial 9004'},
 'light-fluval':{title:'Pantalla marina programable',desc:'Fluval Marine LED controlada por FluvalSmart. El modelo/watios exactos siguen pendientes de confirmar.',specs:['control por canales','ciclo 24 h','amanecer/anochecer','espectro marino'],capabilities:['programar cada canal','crear rampas graduales','guardar perfiles','previsualizar el ciclo'],recommend:'Mientras no haya coral y exista riesgo térmico: usar el perfil de recuperación de la IA, sin luz lunar y con blanco/rosa muy bajos. Cuando vuelva el coral, crear un perfil nuevo según especie y PAR; no reutilizar a ciegas el de recuperación.',source:'Fluval · documentación Marine 3.0'},
 'topoff-reservoir':{title:'Reposición automática',desc:'Sistema con depósito aproximado de 20 L. Marca/modelo aún sin confirmar y actualmente averiado.',specs:['depósito ~20 L','tubería visible','sensor/bomba pendientes de identificar'],capabilities:['reponer evaporación automáticamente','mantener salinidad estable'],recommend:'Es prioritario recuperarlo porque la evaporación veraniega puede mover la salinidad. Debe usar agua RO/DI o agua adecuada de reposición, nunca agua salada para compensar evaporación.',source:'identificación visual pendiente'},
 'salinity-hanna':{title:'Medidor digital de salinidad',desc:'Hanna Marine Salinity Tester.',specs:['medición digital','calibración periódica'],capabilities:['medir salinidad de forma rápida','seguir estabilidad diaria'],recommend:'Usarlo como medidor principal de salinidad y registrar resultado en la app. Calibrar según fabricante antes de tomar la línea base.',source:'Hanna Instruments'},
 'phosphate-hanna':{title:'Checker de fosfato ULR',desc:'Hanna Checker Marine Phosphate ULR.',specs:['rango bajo para marino'],capabilities:['medir PO₄ con precisión útil para reef'],recommend:'Es uno de los tests clave que ya tienes. No comprar otro. Medir antes de usar Nyos Phosphate+.',source:'Hanna Instruments'},
 'nitrate-hanna':{title:'Checker de nitrato HR',desc:'Hanna Checker Marine Nitrate HR HI782.',specs:['nitrato rango alto marino'],capabilities:['seguir NO₃ de forma reproducible'],recommend:'Usarlo para línea base y tendencia. No dosificar Nyos Nitrate+ sin una lectura y objetivo claros.',source:'Hanna Instruments'}
};
function equipmentArt(x){const n=(x.name||'').toLowerCase();if(n.includes('eheim'))return '<div class="prod-art eheim"><span class="generic-badge">IMAGEN GENÉRICA</span><i></i><b>EHEIM<br>4+ 250</b></div>';if(n.includes('nero'))return '<div class="prod-art nero"><span class="generic-badge">IMAGEN GENÉRICA</span><i></i><b>AI NERO 5</b></div>';if(n.includes('tunze'))return '<div class="prod-art tunze"><span class="generic-badge">IMAGEN GENÉRICA</span><i></i><b>TUNZE 9004?</b></div>';if(n.includes('fluval'))return '<div class="prod-art fluval"><span class="generic-badge">IMAGEN GENÉRICA</span><i></i><b>FLUVAL MARINE</b></div>';if(n.includes('hanna')||n.includes('salinity'))return '<div class="prod-art hanna"><span class="generic-badge">IMAGEN GENÉRICA</span><i></i><b>HANNA</b></div>';return `<div class="prod-art generic"><span class="generic-badge">IMAGEN GENÉRICA</span><i></i><b>${esc(x.name||'Equipo')}</b></div>`}
function guideFor(x){const k=equipmentKnowledge[x.id];if(k)return k;return{title:'Equipo registrado',desc:x.notes||'Seguimiento, mantenimiento y diagnóstico.',specs:[],capabilities:['seguimiento de estado'],recommend:'Confirmar modelo y función antes de sustituir.',source:'inventario del propietario'}}
function expertPanel(id,icon,name){const a=expertAdvice[id];return `<button class="expert-card" data-expert="${id}"><span>${icon}</span><div><b>${name}</b><small>${a.verdict}</small></div><em>›</em></button>`}
const advisorViewExpert=advisorView;advisorView=function(){return `<div class="page-intro"><p class="kicker">REEF INTELLIGENCE</p><h2>12 especialistas</h2><p>Cada área emite su recomendación y el sistema forma un consenso para tu Reef 130 L.</p></div><article class="ai-hero"><span>CONSENSO ACTUAL</span><h3>Estabilizar antes de ampliar</h3><p>Analítica Día 0, temperatura, reposición y skimmer primero. Nada de nuevas compras importantes hasta cerrar esos bloqueos.</p><div><em>Coste inmediato 0 €</em><em>Alta prioridad</em></div></article><div class="section-title"><div><p>AJUSTE EXACTO PROPUESTO</p><h2>Nero 5</h2></div></div><article class="exact-profile"><p>Tu captura muestra Random al 30%. La Nero 5 llega a 11.356 L/h, así que en 130 L no necesito llevarla alta. Este es el perfil inicial que aplicaría ahora.</p>${neroProfile.map(r=>`<div><strong>${r[0]}</strong><span>${r[1]}</span><b>${r[2]}</b></div>`).join('')}<small>Feed: mínimo disponible durante 10 min. Mantener las otras dos bombas apagadas o al mínimo hasta identificarlas y comprobar zonas muertas. Random cambia la intensidad automáticamente; no necesita fase.</small></article><div class="section-title"><div><p>AJUSTE EXACTO PROPUESTO</p><h2>Fluval Marine</h2></div></div><article class="exact-profile light"><p>Perfil de recuperación para tu situación actual: sin corales, tapa cerrada, calor en verano y presencia visible de algas. Es deliberadamente más corto y menos blanco que tu ciclo actual.</p><div class="lt head"><b>Hora</b><b>Cian</b><b>Azul</b><b>Morado</b><b>Blanco</b><b>Rosa</b></div>${lightProfile.map(r=>`<div class="lt">${r.map((v,i)=>i===0?`<strong>${v}</strong>`:`<span>${v}%</span>`).join('')}</div>`).join('')}<small>Sin luz lunar. Este NO es el perfil definitivo de coral: cuando tengamos temperatura estable y entre el primer coral, el especialista de esa familia generará otro perfil y una aclimatación gradual. Necesito confirmar el modelo/watios exactos de la Fluval para convertirlo en recomendación definitiva.</small></article><div class="section-title"><div><p>EQUIPO INTERNO</p><h2>Especialistas</h2></div></div><div class="expert-grid">${reefExperts.map(e=>expertPanel(...e)).join('')}</div>`}
const equipmentViewExpert=equipmentView;equipmentView=function(){const groups=[['filtration','Filtración'],['flow','Movimiento'],['skimmer','Skimmer'],['lighting','Iluminación'],['topoff','Reposición'],['test','Medición']];return `<div class="page-intro"><p class="kicker">EQUIPAMIENTO</p><h2>Ficha técnica visual</h2><p>Cada equipo tiene representación genérica, funciones, capacidades y una recomendación específica para tus 130 L.</p></div>${groups.map(([k,n])=>{const xs=state.data.equipment.filter(x=>x.category===k);return xs.length?`<div class="section-title"><div><p>${n.toUpperCase()}</p><h2>${n}</h2></div></div>${xs.map(x=>{const g=guideFor(x);return `<details class="equip-detail"><summary>${equipmentArt(x)}<div><h3>${esc(x.name)}</h3><p>${esc(x.model||'')}</p><span class="state-tag ${x.status==='broken'?'bad':x.status==='unknown'?'pending':'good'}">${x.status==='broken'?'AVERÍA':x.status==='unknown'?'REVISAR':'OK'}</span></div></summary><section><h4>${esc(g.title)}</h4><p>${esc(g.desc)}</p>${g.specs?.length?`<div class="spec-pills">${g.specs.map(s=>`<span>${esc(s)}</span>`).join('')}</div>`:''}<div class="capabilities"><small>QUÉ PUEDE HACER</small>${g.capabilities.map(c=>`<p>✓ ${esc(c)}</p>`).join('')}</div><article><small>RECOMENDACIÓN PARA TU ACUARIO</small><p>${esc(g.recommend)}</p></article><footer>${esc(g.source)}</footer><button class="text-btn" data-entity-type="equipment" data-entity-id="${x.id}">Abrir ficha completa ›</button></section></details>`}).join('')}`:''}).join('')}`}
function showExpert(id){const e=reefExperts.find(x=>x[0]===id),a=expertAdvice[id];if(!e||!a)return;const dlg=$('#entityDialog'),c=$('#entityDialogContent');c.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">ESPECIALISTA</p><h2>${e[1]} ${e[2]}</h2></div><button class="icon-btn" id="closeEntity">×</button></div><article class="ai-hero"><span>VEREDICTO ACTUAL</span><h3>${esc(a.verdict)}</h3><p>${esc(a.why)}</p></article><div class="section-title"><div><p>DATOS QUE EXIGE</p><h2>Antes de decidir</h2></div></div><div class="spec-pills">${a.needs.map(n=>`<span>${esc(n)}</span>`).join('')}</div><article class="info-card"><b>Autoridad dentro del comité</b><p>${esc(a.authority)}.</p></article><article class="info-card"><b>Regla de trabajo</b><p>Si faltan datos, pide mediciones antes de recomendar compras o cambios agresivos. Sus conclusiones se recalculan con inventario, parámetros e historial.</p></article>`;$('#closeEntity').onclick=()=>dlg.close();dlg.showModal()}
const bindDynamicExpert=bindDynamic;bindDynamic=function(){bindDynamicExpert();main.querySelectorAll('[data-expert]').forEach(b=>b.onclick=()=>showExpert(b.dataset.expert));requestAnimationFrame(initFish3D)};
const livestockCardExpert=livestockCard;livestockCard=function(x){return `<div class="life-wrap"><div class="fish3d" data-fish="${esc(x.scientificName)}"><canvas></canvas><small>MODELO 3D GENÉRICO · arrastra para girar</small></div>${livestockCardExpert(x)}</div>`}
function initFish3D(){if(!window.THREE)return;document.querySelectorAll('.fish3d:not([data-ready])').forEach(h=>{h.dataset.ready='1';const w=h.clientWidth||320,hh=155,r=new THREE.WebGLRenderer({canvas:h.querySelector('canvas'),alpha:true,antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.setSize(w,hh,false);const s=new THREE.Scene(),c=new THREE.PerspectiveCamera(35,w/hh,.1,100);c.position.z=5.2;s.add(new THREE.HemisphereLight(0xffffff,0x12303e,2.7));const key=new THREE.DirectionalLight(0xffffff,2);key.position.set(3,3,4);s.add(key);const g=new THREE.Group();s.add(g);const sp=(h.dataset.fish||'').toLowerCase();if(sp.includes('pendiente')){const shell=new THREE.Mesh(new THREE.TorusKnotGeometry(.58,.22,80,12,2,3),new THREE.MeshStandardMaterial({color:0x2a211c,roughness:.72}));shell.scale.set(1,.9,.5);g.add(shell);const foot=new THREE.Mesh(new THREE.SphereGeometry(.58,24,16),new THREE.MeshStandardMaterial({color:0xd9c8a4,roughness:.8}));foot.scale.set(1.35,.3,.42);foot.position.y=-.55;g.add(foot)}else{let bc=0x245fd9,tc=0xf2ce27,sc=[1.35,.72,.4];if(sp.includes('amphiprion')){bc=0xf07820;tc=0xf07820;sc=[1.3,.7,.45]}if(sp.includes('paracanthurus'))sc=[1.48,.86,.34];if(sp.includes('chrysiptera'))sc=[1.15,.58,.34];const body=new THREE.Mesh(new THREE.SphereGeometry(1,42,28),new THREE.MeshStandardMaterial({color:bc,roughness:.34,metalness:.02}));body.scale.set(...sc);g.add(body);const tail=new THREE.Mesh(new THREE.ConeGeometry(.7,.95,3),new THREE.MeshStandardMaterial({color:tc,roughness:.42}));tail.rotation.z=-Math.PI/2;tail.position.x=-1.65;tail.scale.z=.5;g.add(tail);const dorsal=new THREE.Mesh(new THREE.ConeGeometry(.45,.95,3),new THREE.MeshStandardMaterial({color:bc,roughness:.4}));dorsal.position.set(-.1,.86,0);dorsal.scale.z=.18;g.add(dorsal);const eye=new THREE.Mesh(new THREE.SphereGeometry(.075,16,10),new THREE.MeshBasicMaterial({color:0x030303}));eye.position.set(1.12,.21,.34);g.add(eye);if(sp.includes('amphiprion'))[-.58,.18,.7].forEach(x=>{const band=new THREE.Mesh(new THREE.TorusGeometry(.39,.105,10,30),new THREE.MeshStandardMaterial({color:0xf7f4e9,roughness:.35}));band.rotation.y=Math.PI/2;band.position.x=x;band.scale.y=1.48;g.add(band)});if(sp.includes('paracanthurus')){const patch=new THREE.Mesh(new THREE.SphereGeometry(.78,30,18),new THREE.MeshStandardMaterial({color:0x10141b,roughness:.35}));patch.scale.set(1.02,.42,.355);patch.position.set(-.05,.12,.08);g.add(patch)}if(sp.includes('chrysiptera')){body.material.color.setHex(0x2055d8);tail.material.color.setHex(0xf3d320)}}let down=false,lx=0;h.onpointerdown=e=>{down=true;lx=e.clientX;h.setPointerCapture(e.pointerId)};h.onpointermove=e=>{if(down){g.rotation.y+=(e.clientX-lx)*.012;lx=e.clientX}};h.onpointerup=()=>down=false;(function loop(){if(!document.body.contains(h))return;requestAnimationFrame(loop);if(!down)g.rotation.y+=.0022;r.render(s,c)})()})}
