const installationGuides={
 'temp-aquamedic-twin':{icon:'🌡',name:'Aqua Medic T controller twin',status:'Avería parcial',summary:'Controlador de temperatura con salida de calor y salida de frío. El propietario indica que la salida de frío dejó de funcionar.',warning:'No abrir ni reparar internamente un controlador conectado a 230 V junto al acuario. Mantener esa salida fuera de uso hasta sustituir o revisar el equipo por un técnico.',steps:[['Desconecta','Apaga y desenchufa controlador, ventiladores y calentador antes de manipular conexiones.'],['Identifica salidas','Marca claramente HEAT y COOL para evitar intercambiar equipos.'],['Sonda','Coloca la sonda sumergida en una zona con circulación, sin tocar calentador ni salida directa de una bomba.'],['Prueba segura','Cuando tengamos un controlador operativo, prueba cada salida primero con una carga pequeña y visible, manteniendo enchufes y conexiones completamente secos.'],['Programa','Para tu reef de recuperación, el especialista térmico definirá consigna y diferencial después de registrar máximas y mínimas reales durante varios días.']],manual:'https://www.aqua-medic.de/es/Productos/T-controller-twin-20~p5610',video:'https://www.aqua-medic.de/es/Productos/T-controller-twin-20~p5610'},
 'vac-eheim-quick':{icon:'◫',name:'EHEIM Quick Vac pro',status:'Disponible',summary:'Aspirador de fondo a pilas para limpiezas intermedias. Devuelve el agua al acuario después de retener suciedad.',warning:'No usarlo para remover de golpe todo el sustrato acumulado durante años. En tu acuario empezaremos por zonas pequeñas.',steps:[['Monta','Comprueba filtro interno, pilas y cierre antes de introducirlo.'],['Zona pequeña','Trabaja solo una zona del sustrato cada sesión.'],['Sin enterrar','Apoya suavemente la campana; no caves profundamente en la cama de arena.'],['Aclara','Retira y enjuaga el cartucho con agua aparte al terminar.'],['Registra','Guarda en Mantenimiento qué zona has aspirado para rotar el fondo gradualmente.']],manual:'https://eheim.com/es_ES/acuariofilia/accesorios/limpieza/aspirador-de-fondo/quick-vacpro',video:'https://eheim.com/es_ES/acuariofilia/accesorios/limpieza/aspirador-de-fondo/quick-vacpro'},
 'doser-aquamedic-evo':{icon:'◌',name:'Aqua Medic reefdoser EVO',status:'Sin estrenar',summary:'Dosificador Aqua Medic de la familia reefdoser EVO con control por app. El número exacto de canales queda pendiente de confirmar en la etiqueta frontal.',warning:'No instalarlo todavía para dosificar calcio, KH, magnesio, nitrato o fosfato. Primero necesitamos línea base, objetivo y consumo diario real. Automatizar una dosis incorrecta puede empeorar el acuario.',steps:[['Confirma modelo','Haz una foto frontal donde se vea EVO 1, 3 o 5 y la referencia. La app bloqueará la instalación hasta identificarlo.'],['Ubicación seca','Sitúalo siempre fuera de salpicaduras y por encima o protegido frente a posibles sifonados.'],['Tubos','Asigna un tubo por líquido y etiqueta ambos extremos. Nunca mezcles líneas.'],['Calibra cada canal','Antes de usar un aditivo, calibra el canal con agua y un recipiente graduado siguiendo el procedimiento oficial.'],['Primera automatización','Cuando el especialista de química calcule consumo real durante varios días, Acuario AI propondrá ml/día y reparto horario; tú confirmarás antes de activarlo.']],manual:'https://www.aqua-medic.de/es/Productos/Descargas?filter=instruction-manual',video:'https://www.aqua-medic.de/es/Productos/reefdoser-EVO-5~p4562'},
 'fans-submersa-history':{icon:'✣',name:'2 ventiladores Submersa',status:'Averiados',summary:'Dos unidades anteriores terminaron averiándose. Quedan registradas como historial, no como compra recomendada automática.',warning:'Por haber fallado dos unidades, la IA ya no debe considerarlas primera compra por defecto aunque sean baratas.',steps:[['No reutilizar averiados','No conectes ventiladores con signos de corrosión, ruido eléctrico o funcionamiento intermitente.'],['Comparar alternativa','El asesor priorizará coste total, durabilidad, facilidad de sustitución y compra presencial en Cetamar.'],['Control automático','Cualquier nuevo ventilador deberá integrarse con un controlador térmico fiable o una solución equivalente.']],manual:'',video:''}
};
function ensureInstallInventory(){
 if(!state?.data?.equipment)return;
 const extras=[
  {id:'temp-aquamedic-twin',category:'temperature',name:'Aqua Medic T controller twin',model:'modelo previo a 2.0; confirmar etiqueta',status:'broken',confidence:.97,notes:'Controlador visible en fotografía. El propietario indica que la toma de frío dejó de funcionar.'},
  {id:'vac-eheim-quick',category:'maintenance',name:'EHEIM Quick Vac pro',model:'3531000',status:'working',confidence:.99,notes:'Aspirador de fondo confirmado por caja. Apto para agua marina según EHEIM.'},
  {id:'doser-aquamedic-evo',category:'dosing',name:'Aqua Medic reefdoser EVO',model:'familia EVO 1/3/5; canales pendientes de confirmar',status:'unused',confidence:.88,notes:'Equipo comprado y nunca instalado. La caja muestra control por app; confirmar modelo exacto antes de programar.'},
  {id:'fans-submersa-history',category:'temperature',name:'Ventiladores Submersa 120 mm ×2',model:'2 unidades',status:'broken',confidence:1,notes:'Ambas unidades se estropearon; conservar como historial de fiabilidad.'}
 ];
 extras.forEach(x=>{if(!state.data.equipment.some(e=>e.id===x.id))state.data.equipment.push(x)});
 if(typeof equipmentKnowledge!=='undefined'){
  equipmentKnowledge['temp-aquamedic-twin']={title:'Control térmico',desc:'Aqua Medic T controller twin con doble salida calor/frío.',specs:['control simultáneo de calefacción y refrigeración','sonda de temperatura'],capabilities:['activar calentador por temperatura','activar refrigeración por temperatura','mostrar temperatura'],recommend:'La salida de frío está reportada como averiada. No abrir ni reparar la electrónica en casa. Sustituir el controlador antes de automatizar ventiladores.',source:'Aqua Medic + inventario del propietario'};
  equipmentKnowledge['vac-eheim-quick']={title:'Limpieza del sustrato',desc:'EHEIM Quick Vac pro a pilas.',specs:['ref. 3531000','agua marina compatible'],capabilities:['aspirar detrito superficial','devolver agua filtrada al acuario','limpieza intermedia sin cambio de agua'],recommend:'Úsalo por sectores pequeños. No remover todo el fondo de una vez.',source:'EHEIM · ficha oficial'};
  equipmentKnowledge['doser-aquamedic-evo']={title:'Dosificación automática',desc:'Aqua Medic reefdoser EVO con app; modelo exacto pendiente.',specs:['canales calibrables','dosificación manual/automática','programación por app'],capabilities:['dosificar KH/Ca u otros líquidos','repartir dosis en intervalos','automatizar consumos medidos'],recommend:'No usar todavía. Primero medir consumo real y confirmar modelo. Después el Departamento de Instalaciones generará configuración paso a paso.',source:'Aqua Medic · documentación oficial'};
  equipmentKnowledge['fans-submersa-history']={title:'Historial de refrigeración',desc:'Dos ventiladores Submersa previos.',specs:['2 unidades averiadas'],capabilities:['refrigeración evaporativa cuando funcionaban'],recommend:'No repetir compra automáticamente: dos fallos previos pesan negativamente en la recomendación de fiabilidad.',source:'historial del propietario'};
 }
 if(typeof commerceCatalog!=='undefined'){
  commerceCatalog['temp-aquamedic-twin']={replacement:'Aqua Medic T controller twin 2.0 · 205.25',checked:'2026-08-12',offers:[{shop:'Cetamar · recogida presencial',price:58.20,shipping:0,total:58.20,note:'Recogida presencial indicada por el propietario: portes 0 €. Sustituto actual equivalente para controlar calor y frío.',url:'https://www.cetamar.com/es/controladores-de-temperatura/6774-t-controller-twin-20-aqua-medic.html'}],consumables:[],advice:'Por el fallo de la salida de frío, esta sustitución tiene más sentido que comprar otro ventilador sin controlador.'};
  commerceCatalog['vac-eheim-quick']={replacement:'EHEIM Quick Vac pro · 3531000',checked:'2026-08-12',offers:[],consumables:[],advice:'Ya lo tienes. No comprar otro; recuperar su uso dentro de una rutina de limpieza por zonas.'};
  commerceCatalog['doser-aquamedic-evo']={replacement:'Aqua Medic reefdoser EVO',checked:'2026-08-12',offers:[],consumables:[],advice:'Ya lo tienes sin estrenar. Valor potencial alto, gasto inmediato 0 €. Confirmar modelo antes de comprar accesorios o líquidos.'};
 }
}
function installationDepartment(){return `<section class="install-dept"><small>DEPARTAMENTO DE INSTALACIONES</small><h3>Montaje sin improvisar</h3><p>Guías específicas para tu equipo: preparación, instalación, prueba, configuración y verificación final. Cuando un paso implique electricidad cerca del agua, la guía evita reparaciones internas y prioriza seguridad.</p><div class="install-grid">${Object.entries(installationGuides).map(([id,g])=>`<button class="install-card" data-install-guide="${id}"><span>${g.icon}</span><div><b>${g.name}</b><small>${g.status} · ver guía paso a paso</small></div><em>›</em></button>`).join('')}</div><div class="owned-history"><h4>Reglas de este departamento</h4><p>1) identificar modelo exacto; 2) comprobar que ya lo tienes antes de comprar; 3) instalación guiada; 4) prueba sin dosificación peligrosa; 5) validación del especialista correspondiente; 6) solo entonces activar automatización.</p></div></section>`}
function openInstallGuide(id){const g=installationGuides[id];if(!g)return;const dlg=document.querySelector('#entityDialog'),c=document.querySelector('#entityDialogContent');c.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">INSTALACIONES</p><h2>${g.name}</h2></div><button type="button" class="icon-btn" onclick="document.querySelector('#entityDialog').close()">×</button></div><p>${g.summary}</p><div class="install-warning">${g.warning}</div><div class="guide-steps">${g.steps.map((s,i)=>`<div class="guide-step"><span>${i+1}</span><div><b>${s[0]}</b><p>${s[1]}</p></div></div>`).join('')}</div><div class="guide-links">${g.manual?`<a href="${g.manual}" target="_blank" rel="noopener">Manual / ficha oficial</a>`:''}${g.video?`<a href="${g.video}" target="_blank" rel="noopener">Vídeo / recursos oficiales</a>`:''}</div>`;dlg.showModal()}
const equipmentViewInstall=equipmentView;equipmentView=function(){ensureInstallInventory();return equipmentViewInstall()+installationDepartment()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-install-guide]');if(b)openInstallGuide(b.dataset.installGuide)});
