(()=>{
const TODAY='12/08/2026';
const OFFER={
 'Payaso ocellaris':[
  {tag:'Más económica',shop:'MasterFisch',price:13.94,stock:'En stock',shipping:'Envío excluido',url:'https://www.masterfisch.es/peces-marinos-pez-payaso/703-clown-anemonefish-clownfish-bred.html'},
  {tag:'Cercana · recogida',shop:'Cetamar',price:16.00,stock:'Disponible',shipping:'Recogida local 0 €',url:'https://www.cetamar.com/es/peces-payaso/5723-amphiprion-ocellaris-cultivo-talla-s.html'}
 ],
 'Lysmata amboinensis':[{tag:'Oferta',shop:'MasterFisch',price:23.69,stock:'En stock',shipping:'Envío excluido',url:'https://www.masterfisch.es/invertebrados-marinos-crustaceos/985-scarlet-skunk-cleaner-shrimp.html'}],
 'Firefish':[{tag:'Disponible',shop:'MasterFisch',price:41.05,stock:'En stock',shipping:'Envío excluido',url:'https://www.masterfisch.es/peces-marinos-eleotridos/844-magnifica-firefish.html'}],
 'Gobio payaso amarillo':[{tag:'Económica',shop:'MasterFisch',price:18.69,stock:'Disponible',shipping:'Envío excluido',url:'https://www.masterfisch.es/peces-marinos-blenidos-gobios'}],
 'Blenio tailspot':[{tag:'Referencia',shop:'MasterFisch',price:43.10,stock:'Agotado al verificar',shipping:'Envío excluido',url:'https://www.masterfisch.es/peces-marinos-blenidos-gobios/916-tail-spot-blenny.html'}],
 'Gramma loreto':[{tag:'Oferta',shop:'MasterFisch',price:60.36,stock:'En stock',shipping:'Envío excluido',url:'https://www.masterfisch.es/peces-marinos-peces-serranidos/814-royal-gramma.html'}],
 'Chromis verde':[{tag:'Oferta',shop:'MasterFisch',price:9.50,stock:'Disponible',shipping:'Envío excluido',url:'https://www.masterfisch.es/'}],
 'Wrasse six-line':[{tag:'Oferta',shop:'MasterFisch',price:41.77,stock:'Disponible',shipping:'Envío excluido',url:'https://www.masterfisch.es/172-ofertas-10-per-ciento'}],
 'Cangrejo esmeralda':[{tag:'Oferta',shop:'MasterFisch',price:15.57,stock:'Disponible',shipping:'Envío excluido',url:'https://www.masterfisch.es/'}],
 'Lysmata debelius':[{tag:'Disponible',shop:'MasterFisch',price:44.60,stock:'Disponible',shipping:'Envío excluido',url:'https://www.masterfisch.es/'}],
 'Trochus':[{tag:'Oferta',shop:'MasterFisch',price:3.78,stock:'Disponible',shipping:'Envío excluido',url:'https://www.masterfisch.es/178-detritivoros'}]
};
function mny(v){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v)}
function lastFor(key){return [...state.measurements].reverse().find(x=>x.key===key)}
function ageDays(x){if(!x)return Infinity;return (Date.now()-new Date(x.at).getTime())/86400000}
function waterPlan(){
 const t=lastFor('temperature'),s=lastFor('salinity'),no3=lastFor('nitrate'),po4=lastFor('phosphate');
 const tasks=[];
 if(ageDays(t)>1)tasks.push({key:'temperature',name:'Temperatura',when:'Hoy',why:'Es el dato de seguridad inmediato y no requiere gastar nada.',p:1});
 if(ageDays(s)>3)tasks.push({key:'salinity',name:'Salinidad',when:'Hoy',why:'Necesaria antes de decidir cambio de agua o reposición.',p:2});
 if(ageDays(no3)>7)tasks.push({key:'nitrate',name:'Nitrato NO₃',when:'Esta semana',why:'Sirve para decidir si el cambio de agua es necesario y medir tendencia.',p:3});
 if(ageDays(po4)>7)tasks.push({key:'phosphate',name:'Fosfato PO₄',when:'Esta semana',why:'Se interpreta junto a NO₃; no justifica dosificar por sí solo.',p:4});
 return tasks;
}
function homeV16(){const h=health(),tasks=waterPlan();return `<div class="page-intro"><p class="kicker">CENTRO DE MANDO</p><h2>Tu Fluval Flex Marine 123</h2><p>Inicio operativo: primero tareas, después decisiones y compras.</p></div><section class="today-card"><div class="today-top"><div><span class="status-dot"></span><b>${h.label}</b></div><span>${tasks.length} tareas pendientes</span></div><h3>${tasks.length?'Lo siguiente que haría hoy':'Sin tarea urgente registrada'}</h3><p>${tasks[0]?`${tasks[0].name}: ${tasks[0].why}`:'Mantén observación visual y registra cualquier cambio.'}</p>${tasks[0]?`<button class="primary compact" data-measure-key="${tasks[0].key}">Registrar ${tasks[0].name}</button>`:''}</section><div class="control-list"><button class="control-card" data-go="parameters"><span class="control-icon">⌁</span><div><b>Agenda del agua</b><small>${tasks.length?tasks.map(x=>x.name).slice(0,2).join(' · '):'Al día'}</small></div><span>›</span></button><button class="control-card" data-go="proposals"><span class="control-icon">🐠</span><div><b>Propuestas</b><small>Fotos, compatibilidad y precios reales</small></div><span>›</span></button><button class="control-card" data-go="twin"><span class="control-icon">▱</span><div><b>Gemelo digital</b><small>Urna y roca base permanentes</small></div><span>›</span></button><button class="control-card" data-go="advisor"><span class="control-icon">✦</span><div><b>Director Reef</b><small>Prioridades, presupuesto y compras</small></div><span>›</span></button></div><div class="section-title"><div><p>HABITANTES ACTUALES</p><h2>Inventario vivo</h2></div><button class="text-btn" data-go="livestock">Ver todos</button></div><div class="livestock-strip">${state.data.livestock.filter(x=>x.status==='alive').slice(0,8).map(x=>livestockMini(x)).join('')}</div>`}
const WM={temperature:{priority:'1 · HOY',freq:'Diaria mientras estabilizamos',why:'Seguridad térmica y base para decidir refrigeración.'},salinity:{priority:'2 · HOY',freq:'Cada 2–3 días ahora; después semanal si estable',why:'Clave antes y después de cualquier cambio de agua.'},nitrate:{priority:'3 · ESTA SEMANA',freq:'Semanal durante recuperación',why:'Decide si el cambio de agua aporta beneficio real.'},phosphate:{priority:'4 · ESTA SEMANA',freq:'Semanal junto con NO₃',why:'Evita actuar a ciegas con reductores de nutrientes.'},alkalinity:{priority:'NO PRIORITARIO AHORA',freq:'Más adelante según consumo coralino',why:'No lo pondría por delante de temperatura, salinidad, NO₃ y PO₄ en esta fase.'},ph:{priority:'SECUNDARIO',freq:'Cuando los cuatro datos base estén estables',why:'Útil para tendencias, pero no desbloquea la decisión inmediata.'},magnesium:{priority:'NO PRIORITARIO AHORA',freq:'Control ocasional o antes de corregir Ca/KH',why:'No necesita medición frecuente sin consumo calcáreo demostrado.'},calcium:{priority:'NO PRIORITARIO AHORA',freq:'Más adelante',why:'No suplementar ni perseguirlo sin demostrar consumo.'}};
function parametersV16(){const tasks=waterPlan();return `<div class="page-intro"><p class="kicker">AGUA · AGENDA INTELIGENTE</p><h2>Qué necesito que midas</h2><p>No todos los parámetros tienen la misma prioridad. La app los ordena según la fase real del acuario.</p></div><section class="director-card"><small>AGENDA ACTUAL</small><h3>${tasks.length?'Mediciones pendientes':'Mediciones prioritarias al día'}</h3><div class="priority-list">${tasks.map((x,i)=>`<button class="priority-task" data-measure-key="${x.key}"><span>${i+1}</span><div><b>${x.name}</b><small>${x.when} · ${x.why}</small></div><em>Medir ›</em></button>`).join('')||'<div class="blocked-note">No necesitas medir todo hoy. Mantén la rutina y la app volverá a priorizar cuando toque.</div>'}</div></section><div class="section-title"><div><p>TODOS LOS PARÁMETROS</p><h2>Prioridad dinámica</h2></div></div><div class="param-grid">${state.data.parameters.map(p=>{const m=WM[p.key]||{priority:'SECUNDARIO',freq:'Según evolución',why:'Dato complementario.'};return `<button class="parameter-card ${/HOY|ESTA SEMANA/.test(m.priority)?'priority-param':''}" data-water-key="${p.key}"><div><small>${esc(p.name)}</small><strong>${p.latest?esc(p.latest.value):'—'}</strong><span>${esc(p.unit)}</span></div><p>${m.priority}</p><em>${m.freq} · Ver por qué ›</em></button>`}).join('')}</div>`}
function marketBlock(name){const xs=OFFER[name]||[];if(!xs.length)return `<article class="info-card"><b>Dónde comprar</b><p>Sin precio verificado todavía para esta especie. No mostraré cifras inventadas. El radar queda pendiente de comprobación.</p></article>`;return `<div class="section-title"><div><p>COMPRAR</p><h2>Opciones verificadas</h2></div></div>${xs.map(x=>`<article class="info-card"><div class="life-title"><div><h3>${x.tag}</h3><p>${x.shop} · ${x.stock}</p></div><strong>${mny(x.price)}</strong></div><p>${x.shipping} · precio comprobado ${TODAY}.</p><a class="primary" href="${x.url}" target="_blank" rel="noopener">Abrir en ${x.shop}</a></article>`).join('')}`}
async function speciesPhoto(scientific,host){if(!host||!scientific)return;host.innerHTML='<span>Cargando imagen de referencia…</span>';try{const u='https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch='+encodeURIComponent(scientific)+'&gsrlimit=3&prop=pageimages&piprop=thumbnail&pithumbsize=700&format=json&origin=*';const r=await fetch(u);const j=await r.json();const pages=Object.values(j.query?.pages||{});const p=pages.find(x=>x.thumbnail?.source)||pages[0];if(p?.thumbnail?.source)host.innerHTML=`<img src="${esc(p.thumbnail.source)}" alt="${esc(scientific)}"><small>Imagen de referencia · Wikipedia/Wikimedia</small>`;else host.innerHTML='<span>Imagen de referencia no encontrada</span>'}catch(e){host.innerHTML='<span>No se pudo cargar la imagen de referencia</span>'}}
function proposalDetailV16(raw){const [type,name]=raw.split('|');const catalogs=window.__AQ_CATALOG__;const x=catalogs?.[type]?.find(v=>v[0]===name);if(!x)return;const dlg=$('#entityDialog'),c=$('#entityDialogContent'),blocked=/Bloqueado|Riesgo|Ya representado/.test(x[2]);c.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">PROPUESTA · ${type.toUpperCase()}</p><h2>${esc(x[0])}</h2><p>${esc(x[1])}</p></div><button class="icon-btn" id="closeEntity">×</button></div><div id="proposalPhoto" class="profile-photo"><span>Cargando imagen…</span></div><div class="detail-grid"><div class="detail-stat"><small>Evaluación</small><strong>${esc(x[2])}</strong></div><div class="detail-stat"><small>Zona potencial</small><strong>${esc(x[3])}</strong></div></div><article class="info-card"><b>¿Tiene sentido para tu acuario?</b><p>${x[2]==='Ya representado'?'No añadiría más: ya tienes la pareja de ocellaris residente y el historial confirma territorialidad fuerte frente a otros payasos.':blocked?'No lo priorizaría ahora. La ficha se mantiene para explorar el mercado, no como autorización.':'Puede estudiarse, pero antes debe pasar por carga biológica, comportamiento de tus habitantes actuales y analítica.'}</p></article>${marketBlock(x[0])}${!blocked?`<button class="primary" id="sendCandidate">Evaluar compatibilidad completa</button>`:''}`;$('#closeEntity').onclick=()=>dlg.close();const s=$('#sendCandidate');if(s)s.onclick=()=>{dlg.close();go('advisor')};dlg.showModal();speciesPhoto(x[1],document.querySelector('#proposalPhoto'))}
function bindV16(){
 main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
 main.querySelectorAll('[data-measure-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.measureKey;$('#measurementType').value=k;$('#measurementDialog').showModal()});
 main.querySelectorAll('[data-water-key]').forEach(b=>b.onclick=()=>{const key=b.dataset.waterKey,p=state.data.parameters.find(x=>x.key===key),m=WM[key]||{};const dlg=$('#entityDialog'),c=$('#entityDialogContent');c.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">PLAN DE MEDICIÓN</p><h2>${esc(p.name)}</h2></div><button class="icon-btn" id="closeEntity">×</button></div><article class="info-card"><b>Prioridad ahora</b><p>${m.priority||'Secundaria'}</p><b>Frecuencia recomendada</b><p>${m.freq||'Según evolución'}</p><b>Por qué</b><p>${m.why||'Dato complementario.'}</p></article><button class="primary" id="measureThis">Registrar ${esc(p.name)}</button>`;$('#closeEntity').onclick=()=>dlg.close();$('#measureThis').onclick=()=>{dlg.close();$('#measurementType').value=key;$('#measurementDialog').showModal()};dlg.showModal()});
 main.querySelectorAll('[data-proposal]').forEach(b=>b.onclick=()=>proposalDetailV16(b.dataset.proposal));
 main.querySelectorAll('[data-entity-id]').forEach(b=>b.onclick=()=>showEntity(b.dataset.entityType,b.dataset.entityId));
}
function saferTwinView(){return `<div class="page-intro"><p class="kicker">GEMELO DIGITAL</p><h2>Tu aquascape, no un acuario genérico</h2><p>La base se divide en dos islas de roca como en tus fotografías. Las propuestas se muestran como capas separadas para no confundirlas con habitantes actuales.</p></div><section class="twin3-card"><div class="twin3-head"><div><small>FLUVAL FLEX MARINE 123</small><h3>Escena 3D reconstruida</h3></div><span>BETA PRECISIÓN</span></div><div id="reef3d" class="reef3d"><div class="reef3-loading">Cargando gemelo…</div></div><div class="blocked-note">Actual = habitantes/equipo presentes. Propuesta = simulación. No colocaré un coral o pez como “actual” hasta que realmente entre en el acuario.</div></section>`}
// Exponer catálogo existente para conservar datos sin duplicarlos.
if(typeof CATALOG!=='undefined')window.__AQ_CATALOG__=CATALOG;
// proposals.js encapsula CATALOG; reconstruimos el catálogo visible desde sus botones si no quedó expuesto.
if(!window.__AQ_CATALOG__){window.__AQ_CATALOG__={fish:[['Gobio vigilante amarillo','Cryptocentrus cinctus','Condicional','fondo/arena'],['Gobio payaso amarillo','Gobiodon okinawae','Compatible','roca'],['Gobio neón','Elacatinus oceanops','Compatible','roca'],['Firefish','Nemateleotris magnifica','Compatible','cuevas'],['Firefish púrpura','Nemateleotris decora','Compatible','cuevas'],['Blenio bicolor','Ecsenius bicolor','Condicional','roca'],['Blenio tailspot','Ecsenius stigmatura','Compatible','roca'],['Gramma loreto','Gramma loreto','Condicional','cuevas'],['Pseudochromis fridmani','Pseudochromis fridmani','Condicional','cuevas'],['Cardenal Banggai','Pterapogon kauderni','Condicional','columna'],['Chromis verde','Chromis viridis','Condicional','columna'],['Wrasse six-line','Pseudocheilinus hexataenia','Riesgo','roca'],['Payaso ocellaris','Amphiprion ocellaris','Ya representado','columna']],invert:[['Lysmata amboinensis','Lysmata amboinensis','Compatible','roca'],['Lysmata debelius','Lysmata debelius','Compatible','cuevas'],['Thor amboinensis','Thor amboinensis','Compatible','corales'],['Cangrejo esmeralda','Mithraculus sculptus','Condicional','roca'],['Trochus','Trochus sp.','Compatible','roca/cristal'],['Nassarius','Nassarius sp.','Compatible','arena'],['Cerith','Cerithium sp.','Compatible','arena/roca']],coral:[['Zoanthus','Zoanthus sp.','Compatible','baja-media'],['Discosoma','Discosoma sp.','Compatible','baja'],['Ricordea florida','Ricordea florida','Compatible','baja'],['Duncan','Duncanopsammia axifuga','Condicional','media-baja'],['Caulastrea','Caulastrea furcata','Condicional','media'],['Euphyllia hammer','Fimbriaphyllia ancora','Condicional','media'],['Euphyllia frogspawn','Fimbriaphyllia divisa','Condicional','media'],['Euphyllia torch','Euphyllia glabrescens','Condicional','media'],['Micromussa','Micromussa lordhowensis','Condicional','baja-media'],['Blastomussa','Blastomussa sp.','Condicional','baja'],['Goniopora','Goniopora sp.','Condicional','media'],['Montipora digitata','Montipora digitata','Bloqueado ahora','alta']]};}
const OLD_PROPOSALS=window.proposalsView;
window.proposalsView=function(){const C=window.__AQ_CATALOG__;return `<div class="page-intro"><p class="kicker">DEPARTAMENTO DE PROPUESTAS</p><h2>Ideas con foto y coste</h2><p>He eliminado categorías poco claras como “refuerzo roca”. Explora por seres vivos; al pulsar verás imagen, compatibilidad y precios verificados cuando existan.</p></div>${[['fish','Peces'],['invert','Invertebrados'],['coral','Corales']].map(([k,n])=>`<details class="info-card proposal-group" ${k==='fish'?'open':''}><summary><b>${n}</b><span>${C[k].length} candidatos</span></summary><div class="control-list">${C[k].map(x=>`<button class="control-card proposal-entry" data-proposal="${k}|${esc(x[0])}"><span class="control-icon">${k==='fish'?'🐟':k==='invert'?'🦐':'🪸'}</span><div><b>${esc(x[0])}</b><small>${esc(x[1])} · ${esc(x[2])}${OFFER[x[0]]?` · desde ${mny(Math.min(...OFFER[x[0]].map(o=>o.price)))}`:' · precio por verificar'}</small></div><span>›</span></button>`).join('')}</div></details>`).join('')}`};
homeView=homeV16;parametersView=parametersV16;virtualReefView=saferTwinView;
render=function(){try{const views={home:homeView,livestock:livestockView,parameters:parametersView,equipment:equipmentView,twin:virtualReefView,advisor:advisorView,proposals:window.proposalsView};const fn=views[state.view]||homeView;main.innerHTML=fn();bindV16();if(state.view==='twin'&&typeof bindTwin==='function')bindTwin();updateHealth();}catch(err){main.innerHTML=`<div class="empty"><b>La vista ha fallado.</b><p>${esc(err.message)}</p><button class="primary" id="recoverHome">Volver a Inicio</button></div>`;document.querySelector('#recoverHome').onclick=()=>go('home')}};
const style=document.createElement('style');style.textContent=`.profile-photo img{width:100%;height:100%;object-fit:cover}.profile-photo small{position:absolute;left:12px;bottom:10px;background:#071825cc;padding:5px 8px;border-radius:10px}.profile-photo{position:relative;min-height:220px;overflow:hidden}.priority-task{width:100%;text-align:left;border:0;color:inherit;background:transparent}.proposal-entry small{line-height:1.45}.twin3-card .reef3d{min-height:430px}`;document.head.appendChild(style);
})();