(()=>{
const VERIFY='12/08/2026';
const SHIPPING={masterfisch:p=>p>150?0:p>=100?25:29,cetamar:()=>0};
const SELLER_LABEL={MasterFisch:'Entrega a 41020',Cetamar:'Recogida presencial · 0 €'};
function euros(v){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v)}
function currentDue(){
  const latest=k=>[...state.measurements].reverse().find(x=>x.key===k);
  const age=x=>x?(Date.now()-new Date(x.at).getTime())/86400000:Infinity;
  const cfg=[['temperature','Temperatura',1,'Hoy','Seguridad térmica y base para decidir refrigeración.'],['salinity','Salinidad',3,'Hoy','Necesaria antes y después de cualquier cambio de agua.'],['nitrate','Nitrato NO₃',7,'Esta semana','Define tendencia nutritiva y ayuda a decidir cambio de agua.'],['phosphate','Fosfato PO₄',7,'Esta semana','Se interpreta junto con NO₃; evita dosificar a ciegas.']];
  return cfg.filter(x=>age(latest(x[0]))>x[2]).map((x,i)=>({key:x[0],name:x[1],when:x[3],why:x[4],order:i+1}));
}
function maintenanceDue(){const rows=state.maintenance||[];const eheim=[...rows].reverse().find(x=>/eheim|filtro|prefiltro/i.test(`${x.type||''} ${x.detail||''}`));const age=eheim?(Date.now()-new Date(eheim.at).getTime())/86400000:Infinity;return age>45}
function agendaPanel(){const due=currentDue(),filterDue=maintenanceDue();return `<section class="director-card aq-v17-agenda"><small>AGENDA DIARIA · PRIORIDAD REAL</small><h3>${due.length+(filterDue?1:0)?`${due.length+(filterDue?1:0)} tareas que sí importan ahora`:'Prioridades al día'}</h3><p>${due.length?'No te pediré KH, Ca o Mg por rutina mientras no sean necesarios para una decisión.':'No necesitas medir todo. La app volverá a priorizar cuando venza una medición.'}</p><div class="priority-list">${filterDue?`<button class="priority-task" data-v17-maint="eheim"><span>!</span><div><b>Revisar y limpiar EHEIM</b><small>MUY ATRASADO · No limpiar el material biológico bajo el grifo. Aprovecha agua retirada del acuario.</small></div><em>Guía ›</em></button>`:''}${due.map((x,i)=>`<button class="priority-task" data-v17-measure="${x.key}"><span>${i+1+(filterDue?1:0)}</span><div><b>${x.name}</b><small>${x.when} · ${x.why}</small></div><em>Registrar ›</em></button>`).join('')||(!filterDue?'<div class="blocked-note">Observación visual + estabilidad. Sin compras correctoras a ciegas.</div>':'')}</div></section>`}
function eheimGuide(){const dlg=$('#entityDialog'),c=$('#entityDialogContent');c.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">ESPECIALISTA · MANTENIMIENTO</p><h2>Limpieza segura del EHEIM</h2></div><button class="icon-btn" id="closeEntity">×</button></div><article class="info-card"><b>Prioridad: muy alta</b><p>Tras un periodo tan largo sin mantenimiento, hay que inspeccionarlo. No haría una limpieza agresiva simultánea de toda la roca, arena y filtro: queremos recuperar el sistema sin eliminar de golpe demasiada biología.</p></article><article class="info-card"><b>Hazlo durante el próximo cambio de agua</b><p>1. Desenchufa el filtro. 2. Guarda un cubo del agua que acabas de retirar del acuario. 3. Abre el EHEIM y fotografía el orden de las cestas antes de tocarlas. 4. Retira detrito grueso. 5. Aclara esponjas/material biológico suavemente en ese agua vieja del acuario, no bajo la ducha. 6. Limpia rotor e impulsor según el manual del modelo. 7. Monta exactamente en el mismo orden, ceba y comprueba fugas/caudal.</p></article><article class="info-card"><b>Por qué no ducha/grifo para el material biológico</b><p>El agua potable clorada no es la opción que quiero para lavar los medios donde vive la población bacteriana. Para carcasas o piezas no biológicas puede usarse agua limpia si después se aclaran correctamente, pero los medios filtrantes los trataremos con agua retirada del propio acuario.</p></article><article class="info-card"><b>Después</b><p>Registrar fecha, comprobar caudal y observar peces. La app volverá a programar mantenimiento periódico según el filtro exacto y cómo se ensucie realmente, en vez de esperar años.</p></article><button class="primary" id="logEheim">Registrar limpieza terminada</button>`;$('#closeEntity').onclick=()=>dlg.close();$('#logEheim').onclick=()=>{dlg.close();$('#maintenanceType').value='Limpieza prefiltro EHEIM';$('#maintenanceDetail').value='Limpieza segura con agua retirada del acuario';$('#maintenanceDialog').showModal()};dlg.showModal()}
function injectAgenda(){if(!main||!['home','parameters'].includes(state.view)||main.querySelector('.aq-v17-agenda'))return;const wrap=document.createElement('div');wrap.innerHTML=agendaPanel();const node=wrap.firstElementChild;if(state.view==='home')main.insertBefore(node,main.children[1]||null);else main.insertBefore(node,main.firstChild?.nextSibling||null);node.querySelectorAll('[data-v17-measure]').forEach(b=>b.onclick=()=>{$('#measurementType').value=b.dataset.v17Measure;$('#measurementDialog').showModal()});node.querySelectorAll('[data-v17-maint]').forEach(b=>b.onclick=eheimGuide)}
function sellerCostCard(shop,price){const key=shop.toLowerCase(),ship=key.includes('master')?SHIPPING.masterfisch(price):key.includes('cetamar')?0:null;if(ship==null)return '';return `<div class="detail-grid aq-v17-total"><div class="detail-stat"><small>${SELLER_LABEL[shop]||'Coste logístico'}</small><strong>${ship===0?'0 €':euros(ship)}</strong></div><div class="detail-stat"><small>Coste total si compras solo esto</small><strong>${euros(price+ship)}</strong></div></div><small>${shop==='MasterFisch'?'Regla verificada: 29 € hasta 100 €, 25 € entre 100–150 €, gratis por encima de 150 €.':'Para ti se prioriza recogida presencial en Cetamar, por tanto portes 0 €.'} Verificado ${VERIFY}.</small>`}
function enrichMarketDialog(){const c=document.querySelector('#entityDialogContent');if(!c||c.dataset.v17==='1')return;const title=c.querySelector('.sheet-head h2')?.textContent?.trim();if(!title)return;c.dataset.v17='1';[...c.querySelectorAll('article.info-card')].forEach(card=>{const txt=card.textContent||'',shop=txt.includes('MasterFisch')?'MasterFisch':txt.includes('Cetamar')?'Cetamar':null;if(!shop)return;const m=txt.match(/(\d+[\.,]\d{2})\s*€/);if(!m)return;const price=Number(m[1].replace(',','.'));if(!Number.isFinite(price)||card.querySelector('.aq-v17-total'))return;const box=document.createElement('div');box.innerHTML=sellerCostCard(shop,price);while(box.firstChild)card.appendChild(box.firstChild)});const image=c.querySelector('#proposalPhoto img');if(image){image.style.objectFit='contain';image.style.background='transparent'}}
function cleanProposalGroups(){if(state.view!=='proposals')return;main.querySelectorAll('.proposal-group').forEach(g=>{const s=g.querySelector('summary b')?.textContent||'';if(/Equipos de limpieza/i.test(s))g.remove()})}
const oldRender=window.render;window.render=function(){oldRender();requestAnimationFrame(()=>{injectAgenda();cleanProposalGroups()})};
const obs=new MutationObserver(()=>{const d=document.querySelector('#entityDialog');if(d?.open)enrichMarketDialog()});obs.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',()=>{injectAgenda();cleanProposalGroups()});
})();