(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const NERO=[
 {t:'00:00',mode:'Constant',lo:18,hi:18,label:'Noche'},
 {t:'08:00',mode:'Random',lo:20,hi:28,label:'Mañana'},
 {t:'12:00',mode:'Random',lo:24,hi:34,label:'Día'},
 {t:'18:00',mode:'Random',lo:26,hi:38,label:'Tarde'},
 {t:'23:00',mode:'Constant',lo:18,hi:18,label:'Noche'}
];
const LIGHT=[
 {t:'00:00',v:0,label:'OFF'},
 {t:'18:00',v:10,label:'Inicio'},
 {t:'19:00',v:34,label:'Subida'},
 {t:'20:00',v:42,label:'Pico'},
 {t:'22:00',v:28,label:'Bajada'},
 {t:'23:00',v:0,label:'OFF'}
];
function neroUI(){return `<article class="info-card stab-card"><div class="stab-head"><div><small>AI NERO 5 · PROGRAMA RECOMENDADO</small><h3>Una sola bomba de movimiento</h3></div><span class="status-pill warning">FASE ESTABILIZACIÓN</span></div><p>Para 123 L la Nero 5 tiene potencia de sobra. Deja Nero 5 + retornos del Flex y desconecta temporalmente las otras dos bombas. Revisa 48 h si quedan zonas muertas antes de decidir si alguna vuelve.</p><div class="nero-screen"><div class="nero-top"><b>Nero 5</b><span>Schedule</span></div><div class="nero-chart">${NERO.map((x,i)=>`<div class="nero-col" style="--h:${Math.max(x.hi,12)}%"><i></i><small>${x.t}</small></div>`).join('')}</div><div class="nero-points">${NERO.map(x=>`<div><b>${x.t}</b><span>${x.mode}</span><strong>${x.lo===x.hi?x.hi+'%':x.lo+'–'+x.hi+'%'}</strong></div>`).join('')}</div><div class="nero-foot"><b>Feed mode</b><span>1% durante alimentación</span></div></div><div class="blocked-note"><b>Colocación:</b> lateral alto, aproximadamente en el tercio superior, apuntando ligeramente hacia la superficie y en diagonal a lo largo de la urna. Debe ondular la superficie sin levantar arena ni disparar directamente contra los peces.</div></article>`}
function lightUI(){return `<article class="info-card stab-card"><div class="stab-head"><div><small>FLUVAL MARINE 3.0 · VERANO</small><h3>Ciclo temporal para reducir calor</h3></div><span class="status-pill danger">34 °C = URGENTE</span></div><p>Como ahora no hay corales, la prioridad no es PAR: es bajar carga térmica. Mantén la luz apagada durante las horas más calurosas y concentra el fotoperiodo al final del día.</p><div class="fluval-screen"><div class="fluval-tabs"><b>AUTO</b><span>MANUAL</span><span>PRO</span></div><div class="fluval-graph">${LIGHT.map(x=>`<div class="fluval-point" style="--x:${({ '00:00':0,'18:00':60,'19:00':68,'20:00':76,'22:00':88,'23:00':96}[x.t])}%;--y:${100-x.v}%"><i></i><small>${x.t}</small></div>`).join('')}<svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="0,100 60,90 68,66 76,58 88,72 96,100 100,100" fill="none" stroke="currentColor" stroke-width="2.5"/></svg></div><div class="fluval-levels"><div><b>Blancos</b><strong>10–15%</strong></div><div><b>Azules / actínicos</b><strong>35–45%</strong></div><div><b>Pico total</b><strong>20:00</strong></div><div><b>Apagado</b><strong>23:00–18:00</strong></div></div></div><div class="blocked-note">Este es un programa temporal de verano para peces y roca. Cuando el sistema esté estable y volvamos a introducir corales, la IA recalculará espectro, duración y potencia según especies y posición.</div></article>`}
function tempUI(){return `<article class="info-card stab-card"><div class="stab-head"><div><small>TEMPERATURA · PRIORIDAD 0</small><h3>No esperar a septiembre</h3></div><span class="status-pill danger">CRÍTICA</span></div><p>34 °C no es una mejora futura: es un riesgo actual. La prioridad inmediata es destapar la urna cuando sea eléctricamente seguro, reducir la luz en horas de calor y recuperar refrigeración controlada.</p><div class="priority-list"><div class="priority-task"><span>1</span><div><b>Abrir/destapar la urna</b><small>Solo cuando la luminaria quede instalada de forma independiente y segura.</small></div></div><div class="priority-task"><span>2</span><div><b>Aqua Medic T controller twin 2.0</b><small>Calor y frío separados; objetivo inicial 25,5 °C, refrigeración ON a 26,0 °C y calefacción solo si baja de 24,5 °C.</small></div></div><div class="priority-task"><span>3</span><div><b>Refrigeración</b><small>Primero ventilación activa controlada. Si con habitación/calor real no mantiene ≤27 °C, valorar enfriador, no seguir añadiendo ventiladores sin control.</small></div></div></div></article>`}
function cableUI(){return `<article class="info-card stab-card"><small>INSTALACIÓN ELÉCTRICA · ORDEN DEL MUEBLE</small><h3>Cómo quiero dejar los cables</h3><div class="checklist"><p>✓ Regletas y fuentes de alimentación fuera del suelo y de cualquier trayectoria de goteo.</p><p>✓ Cada cable debe formar un <b>bucle de goteo</b> antes de llegar a enchufe/controlador.</p><p>✓ Separar 230 V de tubos de agua y de los puntos donde manipulas garrafas.</p><p>✓ Nada de conexiones sueltas, ladrones o empalmes en la zona húmeda.</p><p>✓ Etiquetas: NERO 5 · RETORNO · EHEIM · SKIMMER · LUZ · CALOR · FRÍO.</p><p>✓ Sujetar cable sobrante verticalmente; no enrollarlo apretado sobre fuentes que se calientan.</p><p>✓ Mantener controlador Aqua Medic y transformadores visibles y accesibles, no enterrados detrás de garrafas.</p></div><div class="blocked-note">Si una toma, regleta o cable presenta humedad, oxidación, calentamiento, plástico cuarteado o reparación casera, no se reutiliza. La app debe marcarlo como sustitución antes de energizarlo.</div></article>`}
function plan(){return `<section class="stab-master"><div class="page-intro"><p class="kicker">PLAN MAESTRO · ESTABILIZACIÓN</p><h2>Primero temperatura, flujo y seguridad</h2><p>Orden definitivo antes de volver a pensar en corales.</p></div>${tempUI()}${neroUI()}${lightUI()}${cableUI()}<article class="info-card"><small>ORDEN DE EJECUCIÓN</small><h3>Secuencia que seguiré contigo</h3><div class="priority-list"><div class="priority-task"><span>0</span><div><b>Temperatura ≤ 27 °C</b><small>No esperar al final del verano.</small></div></div><div class="priority-task"><span>1</span><div><b>20–25 L agua marina + RO/DI para reposición</b><small>Sin cambio del 100%.</small></div></div><div class="priority-task"><span>2</span><div><b>Orden eléctrico + tapa/luz</b><small>Abrir urna de forma segura.</small></div></div><div class="priority-task"><span>3</span><div><b>Nero 5 sola + retornos</b><small>48 h de observación de zonas muertas.</small></div></div><div class="priority-task"><span>4</span><div><b>Limpieza conservadora del EHEIM</b><small>Con agua retirada del acuario.</small></div></div><div class="priority-task"><span>5</span><div><b>Diagnóstico del Tunze 9004</b><small>Reparar antes de comprar otro.</small></div></div></div></article></section>`}
function inject(){if(!window.state||!window.main)return;if(!['home','equipment'].includes(state.view)||main.querySelector('.stab-master'))return;const w=document.createElement('div');w.innerHTML=plan();const n=w.firstElementChild;if(state.view==='home')main.insertBefore(n,main.firstChild?.nextSibling||null);else main.insertBefore(n,main.firstChild||null)}
const st=document.createElement('style');st.textContent=`.stab-master{display:grid;gap:12px;margin:12px 0}.stab-card{overflow:hidden}.stab-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.nero-screen,.fluval-screen{background:#0b0e13;border-radius:18px;padding:14px;margin:12px 0;color:#f7fbff;box-shadow:inset 0 0 0 1px #252d39}.nero-top,.fluval-tabs{display:flex;justify-content:space-between;align-items:center;color:#aeb7c4;font-size:12px}.nero-chart{height:130px;display:flex;align-items:flex-end;justify-content:space-around;border-bottom:1px solid #303846;padding:10px 6px 18px}.nero-col{height:100%;width:15%;display:flex;align-items:flex-end;justify-content:center;position:relative}.nero-col i{width:5px;height:var(--h);min-height:18px;border-radius:5px;background:linear-gradient(#5ed2ff,#1368ff);box-shadow:0 0 12px #248dff88}.nero-col small{position:absolute;bottom:-16px;font-size:9px;color:#8490a0}.nero-points{display:grid;grid-template-columns:repeat(5,1fr);gap:4px;margin-top:12px}.nero-points div{background:#131820;border-radius:9px;padding:6px 3px;text-align:center}.nero-points b,.nero-points span,.nero-points strong{display:block;font-size:9px}.nero-points span{color:#8995a6;margin:3px 0}.nero-points strong{color:#67cfff}.nero-foot{display:flex;justify-content:space-between;margin-top:9px;font-size:11px}.fluval-tabs{justify-content:flex-start;gap:20px}.fluval-tabs b{color:#62cbff;border-bottom:2px solid #62cbff;padding-bottom:6px}.fluval-graph{height:150px;position:relative;margin-top:8px;border-radius:10px;background:linear-gradient(180deg,#111a29,#0c1119)}.fluval-graph svg{position:absolute;inset:0;width:100%;height:100%;color:#5bc7ff}.fluval-point{position:absolute;left:var(--x);top:var(--y);transform:translate(-50%,-50%);z-index:2}.fluval-point i{display:block;width:9px;height:9px;border:2px solid white;background:#2a9dff;border-radius:50%;box-shadow:0 0 10px #45b7ff}.fluval-point small{font-size:8px;color:#d7e5f4;position:absolute;top:12px;left:-10px}.fluval-levels{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px}.fluval-levels div{background:#131820;border-radius:10px;padding:8px}.fluval-levels b,.fluval-levels strong{display:block;font-size:10px}.fluval-levels strong{color:#5ed2ff;margin-top:3px}.checklist p{margin:8px 0;font-size:13px;line-height:1.35}`;document.head.appendChild(st);
const oldRender=window.render;window.render=function(){oldRender();requestAnimationFrame(inject)};window.addEventListener('load',inject);new MutationObserver(()=>inject()).observe(document.body,{childList:true,subtree:true});
})();