const twinModeKey='aq_virtual_reef_mode';
const twinPlacements=[
{id:'clowns',kind:'fish',state:'current',name:'Ocellaris',x:-.5,y:.15,z:.2},{id:'tang',kind:'fish',state:'current',name:'Cirujano azul',x:1.15,y:.25,z:-.2},{id:'damsel',kind:'fish',state:'current',name:'Damisela',x:-1.15,y:.45,z:-.45},{id:'hulk',kind:'coral',state:'proposal',name:'Hulk',x:.35,y:-.82,z:.05},{id:'zoa',kind:'coral',state:'proposal',name:'Zoanthus',x:-1.15,y:-.9,z:.15},{id:'nero',kind:'equipment',state:'equipment',name:'Nero 5',x:2.35,y:.35,z:0},{id:'tunze',kind:'equipment',state:'equipment',name:'Tunze',x:-2.35,y:.15,z:0},{id:'fan',kind:'equipment',state:'proposal',name:'Ventilación',x:1.8,y:1.55,z:0}];
function twinMode(){return localStorage.getItem(twinModeKey)||'all'}
function virtualReefView(){return `<div class="page-intro"><p class="kicker">GEMELO 3D</p><h2>Reef hiperrealista</h2><p>Urna y aquascape permanentes reconstruidos como escena tridimensional. Arrastra para girar, pellizca para zoom y toca elementos para inspeccionarlos.</p></div><section class="twin3-card"><div class="twin3-head"><div><small>FLUVAL FLEX MARINE 123 · ESCENA DIGITAL</small><h3>Tu acuario virtual</h3></div><span>3D LIVE</span></div><div class="twin3-filters"><button data-t3="all">Todo</button><button data-t3="current">Actual</button><button data-t3="proposal">Propuestas</button><button data-t3="equipment">Equipo</button></div><div id="reef3d" class="reef3d"><div class="reef3-loading">Construyendo océano…</div></div><p class="twin-note">La geometría base queda fija. Las altas, bajas y recomendaciones se actualizan como capas de la escena. Las propuestas son simulaciones, no autorización de compra.</p></section><section class="twin-card"><small>SIMULACIÓN PROFESIONAL</small><h3>Prueba el futuro antes de comprar</h3><div class="scenario-list"><button data-t3focus="hulk"><span>✺</span><div><b>Coral LPS Hulk</b><small>Previsualizar escala, altura y separación</small></div><em>Localizar ›</em></button><button data-t3focus="zoa"><span>✹</span><div><b>Zoanthus</b><small>Simular colonia y expansión sobre roca</small></div><em>Localizar ›</em></button><button data-t3focus="fan"><span>≋</span><div><b>Refrigeración</b><small>Visualizar instalación sobre la superficie</small></div><em>Localizar ›</em></button></div></section>`}
function bindTwin(){const host=document.querySelector('#reef3d');if(!host)return;document.querySelectorAll('[data-t3]').forEach(b=>{b.classList.toggle('active',b.dataset.t3===twinMode());b.onclick=()=>{localStorage.setItem(twinModeKey,b.dataset.t3);render()}});loadThree().then(()=>buildReef3D(host));}
function loadThree(){if(window.THREE)return Promise.resolve();return new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function buildReef3D(host){host.innerHTML='';const T=THREE,w=host.clientWidth,h=Math.max(390,Math.round(w*.82)),scene=new T.Scene();scene.background=new T.Color(0x06131d);scene.fog=new T.FogExp2(0x071b27,.055);const camera=new T.PerspectiveCamera(43,w/h,.1,100);camera.position.set(0,1.1,8.3);const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(w,h);renderer.shadowMap.enabled=true;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.appendChild(renderer.domElement);
scene.add(new T.HemisphereLight(0x8adfff,0x071019,1.5));const reefLight=new T.DirectionalLight(0xa7e8ff,3.2);reefLight.position.set(0,5,3);reefLight.castShadow=true;scene.add(reefLight);const blue=new T.PointLight(0x168dff,22,12);blue.position.set(-2,2,2);scene.add(blue);
const glass=new T.MeshPhysicalMaterial({color:0x8dddf0,transparent:true,opacity:.09,roughness:.08,metalness:0,transmission:.55,side:T.DoubleSide});const tank=new T.Mesh(new T.BoxGeometry(5.8,3.25,2.55),glass);tank.position.y=.1;scene.add(tank);const water=new T.Mesh(new T.BoxGeometry(5.65,3.05,2.4),new T.MeshPhysicalMaterial({color:0x0b6688,transparent:true,opacity:.18,roughness:.12,transmission:.5}));water.position.y=.08;scene.add(water);
const sand=new T.Mesh(new T.BoxGeometry(5.45,.14,2.2),new T.MeshStandardMaterial({color:0xd7c9a4,roughness:1}));sand.position.set(0,-1.39,0);sand.receiveShadow=true;scene.add(sand);
const rockMat=new T.MeshStandardMaterial({color:0x7b766c,roughness:.94});function rock(x,y,z,sx,sy,sz,r=0){const g=new T.DodecahedronGeometry(1,2);const m=new T.Mesh(g,rockMat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.rotation.set(r,r*.4,-r*.25);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
rock(-1.45,-.85,.05,1.05,.65,.7,.3);rock(-1.15,-.28,-.12,.9,.78,.62,-.5);rock(-1.55,.28,-.35,.63,.62,.5,.8);rock(-.55,-.75,.22,.72,.48,.62,.2);rock(.75,-.92,.05,1.25,.55,.8,-.2);rock(1.25,-.42,-.15,1.08,.72,.65,.55);rock(1.55,.2,-.35,.72,.65,.5,-.65);rock(.45,-.35,-.35,.75,.48,.55,.1);
const objects={};const mode=twinMode();twinPlacements.filter(p=>mode==='all'||p.state===mode||p.kind===mode).forEach(p=>{let m;if(p.kind==='coral'){const group=new T.Group();for(let i=0;i<7;i++){const ball=new T.Mesh(new T.SphereGeometry(.13+Math.random()*.06,18,14),new T.MeshStandardMaterial({color:p.id==='hulk'?0x39ff79:0x49d98c,emissive:p.id==='hulk'?0x126b2d:0x154b39,emissiveIntensity:1.1,roughness:.55}));ball.position.set((Math.random()-.5)*.38,Math.random()*.2,(Math.random()-.5)*.3);group.add(ball)}m=group}else if(p.kind==='equipment'){m=new T.Mesh(new T.CylinderGeometry(.18,.18,.22,24),new T.MeshStandardMaterial({color:0x151b20,metalness:.5,roughness:.35}));m.rotation.z=Math.PI/2}else{const color=p.id==='tang'?0x1769d2:p.id==='damsel'?0x187dcc:0xf07b23;m=new T.Mesh(new T.SphereGeometry(.22,24,16),new T.MeshStandardMaterial({color,roughness:.38,metalness:.05}));m.scale.set(1.65,.72,.32)}m.position.set(p.x,p.y,p.z);m.userData=p;scene.add(m);objects[p.id]=m});
const clock=new T.Clock();let ry=0,rx=0,zoom=8.3,drag=false,lx=0,ly=0;const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;ry+=(e.clientX-lx)*.006;rx=Math.max(-.25,Math.min(.3,rx+(e.clientY-ly)*.003));lx=e.clientX;ly=e.clientY});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{zoom=Math.max(5.3,Math.min(11,zoom+e.deltaY*.006));e.preventDefault()},{passive:false});let pinch=0;canvas.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)zoom=Math.max(5.3,Math.min(11,zoom-(d-pinch)*.015));pinch=d;e.preventDefault()}},{passive:false});canvas.addEventListener('touchend',()=>pinch=0);
document.querySelectorAll('[data-t3focus]').forEach(b=>b.onclick=()=>{const o=objects[b.dataset.t3focus];if(o){ry=-o.position.x*.08;zoom=6.2}});function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();camera.position.x=Math.sin(ry)*zoom;camera.position.z=Math.cos(ry)*zoom;camera.position.y=1+rx*5;camera.lookAt(0,-.05,0);Object.values(objects).forEach(o=>{if(o.userData.kind==='fish'){o.position.y+=Math.sin(t*1.4+o.position.x)*.0008;o.rotation.y=Math.sin(t*.35+o.position.x)*.18}});renderer.render(scene,camera)}animate();const ro=new ResizeObserver(()=>{const nw=host.clientWidth,nh=Math.max(390,Math.round(nw*.82));camera.aspect=nw/nh;camera.updateProjectionMatrix();renderer.setSize(nw,nh)});ro.observe(host)}
const oldRenderTwin=render;render=function(){const views={home:homeView,livestock:livestockView,parameters:parametersView,equipment:equipmentView,twin:virtualReefView,advisor:advisorView};main.innerHTML=views[state.view]();bindDynamic();if(state.view==='twin')bindTwin();updateHealth()};