const twinKey='aq_virtual_reef_photo';
const twinModeKey='aq_virtual_reef_mode';
const twinPlacements=[
 {id:'current-clowns',kind:'fish',state:'current',name:'Pareja Ocellaris',x:46,y:48,size:13,entityId:'fish-clown-pair',reason:'Habitantes actuales. El gemelo los muestra como referencia móvil, no como posición fija.'},
 {id:'current-tang',kind:'fish',state:'current',name:'Cirujano azul',x:68,y:43,size:12,entityId:'fish-blue-tang-1',reason:'Habitante actual. Su icono representa presencia en el volumen de nado, no territorio fijo.'},
 {id:'current-damsel',kind:'fish',state:'current',name:'Damisela',x:31,y:38,size:9,entityId:'fish-blue-yellow-1',reason:'Habitante actual; identificación visual aún provisional.'},
 {id:'proposal-hulk',kind:'coral',state:'proposal',name:'Caulastrea / Hulk',x:55,y:67,size:12,reason:'Ejemplo de LPS para zona media-baja, con luz moderada y flujo indirecto. Solo se desbloqueará cuando química y temperatura sean estables.',shopHint:'Submersa / Cetamar / especialista LPS'},
 {id:'proposal-zoa',kind:'coral',state:'proposal',name:'Zoanthus',x:32,y:72,size:10,reason:'Ejemplo de colonia blanda para roca baja-media con espacio para expansión. Evitar colocarla pegada a LPS agresivos.',shopHint:'Submersa / Cetamar'},
 {id:'proposal-cleanup',kind:'invertebrate',state:'proposal',name:'Equipo de limpieza',x:73,y:84,size:9,reason:'Caracoles o invertebrados solo según necesidad real de algas/detrito y compatibilidad; no comprar un pack por rutina.',shopHint:'Cetamar / MasterFisch'},
 {id:'equipment-nero',kind:'equipment',state:'equipment',name:'Nero 5',x:92,y:35,size:8,reason:'Representación de la bomba de movimiento. El especialista de flujo ajustará altura, orientación y potencia según zonas muertas y respuesta de los corales.'},
 {id:'equipment-tunze',kind:'equipment',state:'equipment',name:'Tunze 6040',x:8,y:45,size:7,reason:'Segunda fuente de flujo histórica/instalada. Se debe decidir si aporta circulación útil o exceso antes de mantenerla activa.'},
 {id:'equipment-light',kind:'equipment',state:'equipment',name:'Fluval Marine 3.0',x:50,y:5,size:12,reason:'Luminaria actual dentro de la tapa. El gemelo marca su eje para relacionar zonas de luz con futuros corales.'},
 {id:'equipment-fan',kind:'equipment',state:'proposal',name:'Ventilación',x:86,y:7,size:9,reason:'Ubicación virtual de ejemplo: ventilación dirigida a superficie, nunca como compra automática. Temperatura y controlador deben desbloquear esta recomendación.'}
];
function twinPhoto(){return localStorage.getItem(twinKey)||''}
function twinMode(){return localStorage.getItem(twinModeKey)||'all'}
function twinImageFor(p){if(p.entityId){const x=state?.data?.livestock?.find(v=>v.id===p.entityId);return x?.image||''}return''}
function twinVisible(p){const m=twinMode();return m==='all'||m===p.state||m===p.kind}
function twinMarker(p){if(!twinVisible(p))return'';const img=twinImageFor(p);const cls=`twin-marker ${p.state} ${p.kind}`;return `<button class="${cls}" data-twin-id="${p.id}" style="left:${p.x}%;top:${p.y}%;--s:${p.size}vw" aria-label="${esc(p.name)}"><span class="twin-visual">${img?`<img src="${esc(img)}" alt="${esc(p.name)}">`:`<i>${p.kind==='coral'?'✺':p.kind==='equipment'?'⚙':p.kind==='invertebrate'?'◌':'◉'}</i>`}</span><b>${esc(p.name)}</b></button>`}
function twinShelf(){return `<div class="twin-shelf"><button data-twin-filter="all" class="${twinMode()==='all'?'active':''}">Todo</button><button data-twin-filter="current" class="${twinMode()==='current'?'active':''}">Actual</button><button data-twin-filter="proposal" class="${twinMode()==='proposal'?'active':''}">Propuestas</button><button data-twin-filter="equipment" class="${twinMode()==='equipment'?'active':''}">Equipo</button></div>`}
function virtualReefView(){const photo=twinPhoto();return `<div class="page-intro"><p class="kicker">GEMELO DIGITAL</p><h2>Tu reef virtual</h2><p>Una capa visual sobre una foto real de tu propio acuario. Muestra lo actual, lo que propone cada especialista y dónde colocarlo antes de comprar o tocar nada.</p></div>
<section class="twin-card"><div class="twin-head"><div><small>VISTA FRONTAL · FLUVAL FLEX MARINE 123</small><h3>${photo?'Gemelo fotográfico activo':'Añade una foto frontal actual'}</h3></div><span class="twin-live">EN VIVO</span></div>${twinShelf()}<div class="reef-stage ${photo?'has-photo':'no-photo'}" id="reefStage" ${photo?`style="background-image:linear-gradient(rgba(2,10,16,.06),rgba(2,10,16,.16)),url('${photo}')"`:''}>${photo?'':`<div class="twin-empty"><span>▱</span><b>Necesito una foto frontal actual</b><small>El gemelo usará tu propio aquascape como base para que roca, arena y proporciones sean reales.</small></div>`}${twinPlacements.map(twinMarker).join('')}<div class="twin-depth"><span>SUPERFICIE</span><span>MEDIA</span><span>FONDO</span></div></div><div class="twin-actions"><label class="twin-upload">${photo?'Actualizar foto':'Elegir foto del acuario'}<input id="twinPhotoInput" type="file" accept="image/*" capture="environment"></label>${photo?`<button id="twinRemovePhoto" type="button">Quitar foto</button>`:''}</div><p class="twin-note">Los peces se representan como presencia en el volumen de nado; corales y equipos sí usan puntos de colocación. Una propuesta virtual nunca equivale a autorización de compra.</p></section>
<section class="twin-card"><small>ESCENARIOS DEL ESPECIALISTA</small><h3>Ver antes de comprar</h3><div class="scenario-list"><button data-twin-focus="proposal-hulk"><span>✺</span><div><b>LPS verde tipo Hulk</b><small>Zona media-baja · flujo indirecto · ejemplo bloqueado</small></div><em>Ver sitio ›</em></button><button data-twin-focus="proposal-zoa"><span>✹</span><div><b>Zoanthus</b><small>Roca baja-media · crecimiento controlable</small></div><em>Ver sitio ›</em></button><button data-twin-focus="equipment-fan"><span>≋</span><div><b>Refrigeración</b><small>Simular ubicación y sentido de aire sobre superficie</small></div><em>Ver sitio ›</em></button></div></section>
<section class="twin-card"><small>MODELO PROFESIONAL</small><h3>Qué actualizará automáticamente</h3><div class="twin-features"><div><b>Inventario</b><small>Altas y bajas aparecen/desaparecen del gemelo.</small></div><div><b>Especialistas</b><small>Una recomendación crea una previsualización, no una compra.</small></div><div><b>Ubicación</b><small>Cada coral guarda zona, altura, luz y flujo objetivo.</small></div><div><b>Equipamiento</b><small>Bombas, luz y refrigeración se muestran con posición y función.</small></div></div></section>`}
function openTwinDetail(id){const p=twinPlacements.find(x=>x.id===id);if(!p)return;const dlg=document.querySelector('#entityDialog'),c=document.querySelector('#entityDialogContent');const entity=p.entityId?state.data.livestock.find(x=>x.id===p.entityId):null;c.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">GEMELO REEF</p><h2>${esc(p.name)}</h2></div><button class="icon-btn" id="closeTwin">×</button></div>${entity?.image?`<div class="profile-photo"><img src="${esc(entity.image)}" alt="${esc(p.name)}"></div>`:''}<article class="info-card"><b>${p.state==='proposal'?'Propuesta del especialista':p.state==='equipment'?'Posición de equipo':'Habitante actual'}</b><p>${esc(p.reason)}</p></article>${p.shopHint?`<article class="info-card"><b>Si algún día se autoriza la compra</b><p>${esc(p.shopHint)}. El Director Financiero exigirá 2–3 opciones, coste total y compatibilidad antes de comprar.</p></article>`:''}`;document.querySelector('#closeTwin').onclick=()=>dlg.close();dlg.showModal()}
function bindTwin(){document.querySelectorAll('[data-twin-id]').forEach(b=>b.onclick=()=>openTwinDetail(b.dataset.twinId));document.querySelectorAll('[data-twin-filter]').forEach(b=>b.onclick=()=>{localStorage.setItem(twinModeKey,b.dataset.twinFilter);render()});document.querySelectorAll('[data-twin-focus]').forEach(b=>b.onclick=()=>{const id=b.dataset.twinFocus;localStorage.setItem(twinModeKey,'all');render();setTimeout(()=>{const m=document.querySelector(`[data-twin-id="${id}"]`);m?.scrollIntoView({behavior:'smooth',block:'center'});m?.classList.add('pulse');setTimeout(()=>m?.classList.remove('pulse'),1800)},30)});const input=document.querySelector('#twinPhotoInput');if(input)input.onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/img.width),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);localStorage.setItem(twinKey,canvas.toDataURL('image/jpeg',.86));render()};img.src=r.result};r.readAsDataURL(f)};const rm=document.querySelector('#twinRemovePhoto');if(rm)rm.onclick=()=>{localStorage.removeItem(twinKey);render()}}
const oldRenderTwin=render;render=function(){const views={home:homeView,livestock:livestockView,parameters:parametersView,equipment:equipmentView,twin:virtualReefView,advisor:advisorView};main.innerHTML=views[state.view]();bindDynamic();if(state.view==='twin')bindTwin();updateHealth()};
