import * as THREE from 'https://unpkg.com/three@0.169.0/build/three.module.js';
import {fbm3,noise3} from './geometry-hull.js';

const C=new THREE.Color();
function bounds(pts){let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const p of pts){minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])}return{minX,maxX,minY,maxY}}
function shapeFrom(points){const s=new THREE.Shape();s.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)s.lineTo(points[i][0],points[i][1]);s.closePath();return s}
function addFrontVoids(shape,island){for(const v of island.voids||[]){if(v.plane!=='front'||!v.polygon?.length)continue;const h=new THREE.Path();h.moveTo(v.polygon[0][0],v.polygon[0][1]);for(let i=1;i<v.polygon.length;i++)h.lineTo(v.polygon[i][0],v.polygon[i][1]);h.closePath();shape.holes.push(h)}}
function rockMaterial(){return new THREE.MeshStandardMaterial({vertexColors:true,roughness:.93,metalness:0,side:THREE.DoubleSide})}
function paint(geo,condition,seed){const pos=geo.attributes.position,n=pos.count,colors=new Float32Array(n*3),p=condition.palette,base=new THREE.Color(p.rockBase),ochre=new THREE.Color(p.rockOchre),purple=new THREE.Color(p.rockPurple),pink=new THREE.Color(p.corallinePink),green=new THREE.Color(p.algaeGreen),dark=new THREE.Color(p.detritusDark);for(let i=0;i<n;i++){const x=pos.getX(i),y=pos.getY(i),z=pos.getZ(i),macro=fbm3((x+seed)*.085,y*.085,(z-seed)*.085,3)*.5+.5,micro=noise3(x*.28+seed,y*.28,z*.28)*.5+.5;C.copy(base).lerp(ochre,.28+.48*macro);const coral=Math.max(0,(micro-.47)*1.8)*condition.coralline;C.lerp(purple,Math.min(.46,coral));C.lerp(pink,Math.min(.18,coral*.45));const lower=THREE.MathUtils.clamp((13-y)/13,0,1),algae=lower*condition.greenAlgae*(.25+.55*micro);C.lerp(green,Math.min(.35,algae));const dirt=lower*condition.detritus*(.18+.35*(1-macro));C.lerp(dark,Math.min(.28,dirt));colors[i*3]=C.r;colors[i*3+1]=C.g;colors[i*3+2]=C.b}geo.setAttribute('color',new THREE.BufferAttribute(colors,3))}
function roughen(geo,seed){const p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),n=fbm3((x+seed)*.18,(y-seed)*.18,z*.18,3),fine=noise3(x*.55,y*.55,z*.55);const amp=.32+.22*Math.max(0,1-y/34);p.setXYZ(i,x+n*.52+fine*.12,y+n*.35,z+n*.55+fine*.10)}p.needsUpdate=true;geo.computeVertexNormals();geo.computeBoundingSphere()}
function buildIsland(island,condition,index){const front=island.silhouettes.front,top=island.silhouettes.top,zb=bounds(top),shape=shapeFrom(front);addFrontVoids(shape,island);const depth=Math.max(7,zb.maxY-zb.minY),geo=new THREE.ExtrudeGeometry(shape,{depth,steps:5,bevelEnabled:true,bevelSegments:2,bevelSize:.55,bevelThickness:.45,curveSegments:4});geo.translate(0,0,zb.minY);roughen(geo,13.7+index*19.1);paint(geo,condition,7.3+index*11.8);const mesh=new THREE.Mesh(geo,rockMaterial());mesh.name=island.id;mesh.castShadow=mesh.receiveShadow=true;mesh.renderOrder=1;return mesh}
function buildSand(tank,sand){const geo=new THREE.PlaneGeometry(tank.outerWidth-1.5,tank.outerDepth+tank.frontBow-2,72,40);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position,colors=new Float32Array(pos.count*3),base=new THREE.Color(sand.color),det=new THREE.Color(sand.detritusTint);for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),back=THREE.MathUtils.clamp((-z+10)/28,0,1),dune=fbm3(x*.11,0,z*.11,3)*sand.duneAmplitude,ripple=Math.sin(x*.62+z*.19)*.10;pos.setY(i,THREE.MathUtils.lerp(sand.baseLevel,sand.backLevel,back)+dune+ripple);const dirt=THREE.MathUtils.clamp(sand.detritusAmount*(.25+.7*(noise3(x*.2+4,2,z*.2)*.5+.5))*(.55+back),0,.72);C.copy(base).lerp(det,dirt);colors[i*3]=C.r;colors[i*3+1]=C.g;colors[i*3+2]=C.b}geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.98,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geo,mat);mesh.name='sand';mesh.receiveShadow=true;mesh.renderOrder=0;mesh.userData.material=mat;return mesh}
export function buildAquascape(manifest){const group=new THREE.Group();group.name='aquascape';const materials=[],meshes=[];let triangles=0;manifest.scape.islands.forEach((island,i)=>{const mesh=buildIsland(island,manifest.scape.condition,i);group.add(mesh);meshes.push(mesh);materials.push(mesh.material);triangles+=mesh.geometry.index?mesh.geometry.index.count/3:mesh.geometry.attributes.position.count/3});const sand=buildSand(manifest.tank,manifest.sand);group.add(sand);materials.push(sand.material);function solidity(x,y,z){for(const mesh of meshes){const b=new THREE.Box3().setFromObject(mesh);if(b.containsPoint(new THREE.Vector3(x,y,z)))return 1}return-1}return{group,materials,solidity,stats:{triangles:Math.round(triangles),islands:meshes.length,mode:'photo-traced-extrusion'}}}
