import * as THREE from 'https://unpkg.com/three@0.169.0/build/three.module.js';
import { buildIslandField, surfaceNets, cavityOpenness, fbm3, noise3 } from './geometry-hull.js';

const c = new THREE.Color();
function rockMaterial(palette) {
  const mat = new THREE.MeshStandardMaterial({ vertexColors:true, roughness:1, metalness:0, flatShading:false });
  mat.userData.uniforms={uTime:{value:0}};
  mat.onBeforeCompile=(shader)=>{
    shader.uniforms.uTime=mat.userData.uniforms.uTime; mat.userData.shader=shader;
    shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vWorld;\nvarying vec3 vObj;').replace('#include <worldpos_vertex>','#include <worldpos_vertex>\n vWorld=(modelMatrix*vec4(transformed,1.0)).xyz;\n vObj=position;');
    shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>
uniform float uTime; varying vec3 vWorld; varying vec3 vObj;
float h31(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);} float vnoise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(mix(h31(i),h31(i+vec3(1,0,0)),f.x),mix(h31(i+vec3(0,1,0)),h31(i+vec3(1,1,0)),f.x),f.y),mix(mix(h31(i+vec3(0,0,1)),h31(i+vec3(1,0,1)),f.x),mix(h31(i+vec3(0,1,1)),h31(i+vec3(1,1,1)),f.x),f.y),f.z);} float fbmf(vec3 p){float s=0.0,a=0.5;for(int i=0;i<4;i++){s+=a*vnoise(p);p*=2.07;a*=0.5;}return s;} float caustic(vec2 p,float t){float a=fbmf(vec3(p*0.9,t*0.10));float b=fbmf(vec3(p*1.7+13.0,t*0.14));return pow(max(1.0-abs(a-b)*3.2,0.0),4.0);}`)
    .replace('#include <normal_fragment_maps>',`#include <normal_fragment_maps> {float e=0.35;vec3 q=vObj*1.9;float n0=fbmf(q);vec3 gradN=vec3(fbmf(q+vec3(e,0,0))-n0,fbmf(q+vec3(0,e,0))-n0,fbmf(q+vec3(0,0,e))-n0);vec3 q2=vObj*6.5;float n1=fbmf(q2);vec3 gradP=vec3(fbmf(q2+vec3(e,0,0))-n1,fbmf(q2+vec3(0,e,0))-n1,fbmf(q2+vec3(0,0,e))-n1);normal=normalize(normal-gradN*2.6-gradP*1.1);}`)
    .replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\n roughnessFactor=clamp(0.72+fbmf(vObj*3.1)*0.45,0.45,1.0);')
    .replace('#include <dithering_fragment>','#include <dithering_fragment>\n {float depthFade=smoothstep(0.0,26.0,vWorld.y);float cau=caustic(vWorld.xz*0.11,uTime)*(0.25+0.55*depthFade);gl_FragColor.rgb+=vec3(0.42,0.62,0.70)*cau*0.55;}');
  };
  mat.userData.palette=palette; return mat;
}
function paintIsland(positions,normals,field,condition){const p=condition.palette,base=new THREE.Color(p.rockBase),ochre=new THREE.Color(p.rockOchre),purple=new THREE.Color(p.rockPurple),pink=new THREE.Color(p.corallinePink),algae=new THREE.Color(p.algaeGreen),dark=new THREE.Color(p.detritusDark),n=positions.length/3,colors=new Float32Array(n*3);for(let v=0;v<n;v++){const x=positions[v*3],y=positions[v*3+1],z=positions[v*3+2],nx=normals[v*3],ny=normals[v*3+1],nz=normals[v*3+2],open=cavityOpenness(field,x,y,z,nx,ny,nz),stain=fbm3(x*.09,y*.09,z*.09,3)*.5+.5,patch=noise3(x*.22+4.1,y*.22,z*.22-2.7)*.5+.5;c.copy(base).lerp(ochre,stain);const exposure=Math.max(0,ny*.6+nz*.4)*open,coralline=Math.max(0,(patch-.52)*3)*exposure*condition.coralline*2.4;c.lerp(purple,Math.min(.85,coralline*.6));c.lerp(pink,Math.min(.6,coralline*.35));const light=1-Math.min(1,Math.abs(y-9)/14),green=light*Math.max(0,nz)*condition.greenAlgae*(.5+patch*.9);c.lerp(algae,Math.min(.55,green));const settle=Math.max(0,ny)*(1-open)+(1-open)*.6;c.lerp(dark,Math.min(.8,settle*condition.detritus*1.5));if(y>condition.cleanZonesY)c.lerp(ochre,Math.min(.3,(y-condition.cleanZonesY)*.04));colors[v*3]=c.r;colors[v*3+1]=c.g;colors[v*3+2]=c.b}return colors}
function buildSand(tank,sand,footprint){const geo=new THREE.PlaneGeometry(tank.outerWidth,tank.outerDepth+tank.frontBow,96,52);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position,colors=new Float32Array(pos.count*3),sandCol=new THREE.Color(sand.color),detCol=new THREE.Color(sand.detritusTint);for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),back=THREE.MathUtils.clamp((-z+12)/30,0,1),dune=fbm3(x*.09,0,z*.09,3)*sand.duneAmplitude,ripple=Math.sin(x*.55+z*.2)*.12;pos.setY(i,THREE.MathUtils.lerp(sand.baseLevel,sand.backLevel,back)+dune+ripple);const dirt=THREE.MathUtils.clamp(sand.detritusAmount*(.4+.9*(fbm3(x*.16+7,2,z*.16,2)*.5+.5))*(.5+back),0,1);c.copy(sandCol).lerp(detCol,dirt);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b}geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.95,metalness:0}),mesh=new THREE.Mesh(geo,mat);mesh.receiveShadow=true;mesh.name='sand';mesh.userData.material=mat;mesh.geometry.userData.footprint=footprint;return mesh}
export function buildAquascape(manifest,footprint){const group=new THREE.Group();group.name='aquascape';const condition=manifest.scape.condition,material=rockMaterial(condition.palette),materials=[material],fields=[];let triangles=0;for(const island of manifest.scape.islands){const{field,box}=buildIslandField(island),res=island.voxelSize||.8,{positions,normals,indices}=surfaceNets(field,box,res);if(!positions.length)continue;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('normal',new THREE.BufferAttribute(normals,3));geo.setAttribute('color',new THREE.BufferAttribute(paintIsland(positions,normals,field,condition),3));geo.setIndex(indices);geo.computeBoundingSphere();const mesh=new THREE.Mesh(geo,material);mesh.name=island.id;mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);fields.push(field);triangles+=indices.length/3}const sand=buildSand(manifest.tank,manifest.sand,footprint);group.add(sand);materials.push(sand.userData.material);function solidity(x,y,z){let best=-1e9;for(const f of fields){const v=f(x,y,z);if(v>best)best=v}return best}return{group,materials,solidity,stats:{triangles,islands:fields.length}}}
