import * as THREE from 'https://unpkg.com/three@0.169.0/build/three.module.js';

function halfHeight(t){const h=0.052+0.245*Math.sin(Math.pow(Math.min(1,t*1.18),0.72)*Math.PI)-0.06*Math.pow(t,2.4);return Math.max(0.028,h)}
function halfWidth(t){return halfHeight(t)*(0.62-0.22*t)+0.012*(1-t)}
function centerY(t){return 0.018*Math.sin(t*Math.PI*0.9)-0.01*t}
const SECTIONS=28,RING=14;
function buildBody(L){const bodyLen=L*0.78,positions=[],normals=[],uvs=[],indices=[];for(let i=0;i<SECTIONS;i++){const t=i/(SECTIONS-1),z=bodyLen*(0.5-t),hh=halfHeight(t)*L,hw=halfWidth(t)*L,cy=centerY(t)*L;for(let j=0;j<RING;j++){const a=(j/RING)*Math.PI*2,ca=Math.cos(a),sa=Math.sin(a),belly=sa<0?1.12:1.0,x=hw*Math.sign(ca)*Math.pow(Math.abs(ca),0.82),y=cy+hh*Math.sign(sa)*Math.pow(Math.abs(sa),belly);positions.push(x,y,z);uvs.push(t,j/RING);normals.push(0,0,0)}}for(let i=0;i<SECTIONS-1;i++)for(let j=0;j<RING;j++){const j2=(j+1)%RING,a=i*RING+j,b=i*RING+j2,cIdx=(i+1)*RING+j2,d=(i+1)*RING+j;indices.push(a,b,cIdx,a,cIdx,d)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geo.setIndex(indices);geo.computeVertexNormals();return geo}
function buildFin(samples){const positions=[],uvs=[],indices=[],n=samples.length;for(let i=0;i<n;i++){const s=samples[i];positions.push(s.bx,s.by,s.bz);uvs.push(i/(n-1),0);positions.push(s.tx,s.ty,s.tz);uvs.push(i/(n-1),1)}for(let i=0;i<n-1;i++){const a=i*2,b=i*2+1,c=i*2+2,d=i*2+3;indices.push(a,b,d,a,d,c)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geo.setIndex(indices);geo.computeVertexNormals();return geo}
function dorsalFin(L){const bodyLen=L*0.78,s=[],n=16;for(let i=0;i<n;i++){const k=i/(n-1),t=0.18+k*0.68,z=bodyLen*(0.5-t),by=(centerY(t)+halfHeight(t))*L*0.96,spiny=Math.sin(Math.min(1,k/0.45)*Math.PI)*0.09,soft=k>0.45?Math.sin(((k-0.45)/0.55)*Math.PI)*0.105:0,h=(spiny+soft)*L;s.push({bx:0,by,bz:z,tx:0,ty:by+h,tz:z+h*0.18})}return buildFin(s)}
function analFin(L){const bodyLen=L*0.78,s=[],n=10;for(let i=0;i<n;i++){const k=i/(n-1),t=0.58+k*0.3,z=bodyLen*(0.5-t),by=(centerY(t)-halfHeight(t))*L*0.96,h=Math.sin(k*Math.PI)*0.075*L;s.push({bx:0,by,bz:z,tx:0,ty:by-h,tz:z+h*0.25})}return buildFin(s)}
function caudalFin(L){const bodyLen=L*0.78,z0=-bodyLen*0.5,hh=halfHeight(1)*L,s=[],n=14;for(let i=0;i<n;i++){const k=i/(n-1),a=(k-0.5)*Math.PI,by=Math.sin(a)*hh*1.05,spread=Math.cos(a*0.85),len=(0.19+0.045*spread)*L;s.push({bx:0,by,bz:z0,tx:0,ty:Math.sin(a)*hh*3.05,tz:z0-len})}return buildFin(s)}
function pectoralFin(L,side){const bodyLen=L*0.78,t=0.32,z=bodyLen*(0.5-t),hw=halfWidth(t)*L,s=[],n=8;for(let i=0;i<n;i++){const k=i/(n-1),a=(k-0.5)*1.5,by=Math.sin(a)*0.05*L;s.push({bx:side*hw*0.85,by,bz:z,tx:side*(hw*0.85+Math.cos(a)*0.13*L),ty:by+Math.sin(a)*0.05*L,tz:z-0.06*L})}return buildFin(s)}
const SWIM_CHUNK=`uniform float uTime;uniform float uAmp;uniform float uFreq;uniform float uWave;uniform float uFin;vec3 swim(vec3 p,float u){float amp=uAmp*(0.06+pow(clamp(u,0.0,1.0),2.0));float phase=uTime*uFreq-u*uWave;p.x+=sin(phase)*amp;p.y+=sin(phase*0.5+1.7)*amp*0.12;return p;}`;
function bodyMaterial(seed){return new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uAmp:{value:0.55},uFreq:{value:5.2},uWave:{value:4.4},uFin:{value:0},uSeed:{value:seed},uLight:{value:new THREE.Vector3(0.25,1,0.35)}},vertexShader:`${SWIM_CHUNK} varying vec2 vUv;varying vec3 vN;void main(){vUv=uv;vec3 p=swim(position,uv.x);vN=normalize(normalMatrix*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`,fragmentShader:`varying vec2 vUv;varying vec3 vN;uniform float uSeed;uniform vec3 uLight;float h21(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n2(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(h21(i),h21(i+vec2(1,0)),f.x),mix(h21(i+vec2(0,1)),h21(i+vec2(1,1)),f.x),f.y);}void main(){float u=vUv.x,v=vUv.y,flank=abs(sin(v*6.2831853)),wob=(n2(vec2(v*7.0+uSeed,u*4.0))-0.5)*0.028,c1=0.175+wob,w1=0.055,c2=0.505-0.055*flank+wob,w2=0.075+0.02*flank,c3=0.845+wob,w3=0.038,d=min(min(abs(u-c1)-w1,abs(u-c2)-w2),abs(u-c3)-w3);vec3 orange=mix(vec3(0.94,0.36,0.06),vec3(0.99,0.60,0.22),smoothstep(-0.2,1.0,-cos(v*6.2831853)*0.5+0.5)),white=vec3(0.96,0.96,0.93),black=vec3(0.05,0.04,0.04);vec3 col=orange;col=mix(col,black,smoothstep(0.016,0.004,abs(d)));col=mix(col,white,smoothstep(0.004,-0.004,d));vec3 N=normalize(vN);float diff=clamp(dot(N,normalize(uLight)),0.0,1.0),rim=pow(1.0-abs(N.z),2.5);col*=0.42+0.72*diff;col+=vec3(0.35,0.55,0.65)*rim*0.25;gl_FragColor=vec4(col,1.0);#include <colorspace_fragment>}`})}
function finMaterial(seed,kind){return new THREE.ShaderMaterial({side:THREE.DoubleSide,transparent:true,uniforms:{uTime:{value:0},uAmp:{value:0.55},uFreq:{value:5.2},uWave:{value:4.4},uFin:{value:kind==='pectoral'?1:0},uSeed:{value:seed}},vertexShader:`${SWIM_CHUNK} varying vec2 vUv;void main(){vUv=uv;float u=uFin>0.5?0.35:clamp(0.5-position.z/6.0,0.0,1.2);vec3 p=swim(position,u);if(uFin>0.5){float f=sin(uTime*uFreq*1.9+uSeed)*0.5,k=uv.y;p.x+=f*k*abs(p.x)*0.9;p.z-=abs(f)*k*0.08;}p.y+=sin(uTime*3.1+uv.x*6.0+uSeed)*uv.y*0.035;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`,fragmentShader:`varying vec2 vUv;void main(){vec3 orange=vec3(0.95,0.45,0.10),white=vec3(0.95),black=vec3(0.05,0.04,0.04),col=mix(orange,white,smoothstep(0.55,1.0,vUv.y)*0.7);col=mix(col,black,smoothstep(0.86,1.0,vUv.y));gl_FragColor=vec4(col,0.92);#include <colorspace_fragment>}`})}
/** Fábricas de geometría por especie; una entrada = un renderer PRODUCTION/BETA real. */
export const RENDERERS = {'Amphiprion ocellaris':(lengthCm,seed)=>createOcellaris(lengthCm,seed)};

export function createOcellaris(lengthCm,seed=Math.random()*10){const L=lengthCm,group=new THREE.Group(),mats=[],bMat=bodyMaterial(seed);mats.push(bMat);group.add(new THREE.Mesh(buildBody(L),bMat));const add=(geo,kind)=>{const m=finMaterial(seed,kind);mats.push(m);group.add(new THREE.Mesh(geo,m))};add(dorsalFin(L),'dorsal');add(analFin(L),'anal');add(caudalFin(L),'caudal');add(pectoralFin(L,1),'pectoral');add(pectoralFin(L,-1),'pectoral');const bodyLen=L*0.78,eyeT=0.13,eyeZ=bodyLen*(0.5-eyeT),eyeGeo=new THREE.SphereGeometry(L*0.045,12,10),eyeMat=new THREE.MeshBasicMaterial({color:0x0a0a0c});for(const s of[1,-1]){const e=new THREE.Mesh(eyeGeo,eyeMat);e.position.set(s*halfWidth(eyeT)*L*0.82,centerY(eyeT)*L+L*0.045,eyeZ);group.add(e)}group.userData.materials=mats;return group}
const _v=new THREE.Vector3(),_probe=new THREE.Vector3(),_corr=new THREE.Vector3(),_q=new THREE.Quaternion(),_m=new THREE.Matrix4(),UP=new THREE.Vector3(0,1,0);
export class Swimmer{constructor({id,mesh,lengthCm,personality,home}){this.id=id;this.mesh=mesh;this.L=lengthCm;this.p=personality||{};this.home=home.clone();this.pos=home.clone();this.vel=new THREE.Vector3(1,0,0.2).multiplyScalar(lengthCm*1.4);this.phase=Math.random()*100;this.burst=0;this.nextBurst=2+Math.random()*6;this.mesh.position.copy(this.pos)}update(dt,world,others){const cruise=this.L*1.6*(this.p.cruise??1),bold=this.p.boldness??0.5;this.phase+=dt;const w=this.phase*0.55+this.id.length;_v.set(Math.sin(w*0.9)+Math.sin(w*0.37)*0.6,Math.sin(w*0.23)*0.35,Math.cos(w*0.8)+Math.cos(w*0.41)*0.5).normalize();const acc=_v.multiplyScalar(cruise*1.6);acc.add(_probe.copy(this.home).sub(this.pos).multiplyScalar(0.35*(1.1-bold)));const ahead=_probe.copy(this.vel).normalize().multiplyScalar(this.L*2.2).add(this.pos),s=world.solidity(ahead.x,ahead.y,ahead.z);if(s>-this.L*0.9){const h=1.2,gx=world.solidity(ahead.x+h,ahead.y,ahead.z)-world.solidity(ahead.x-h,ahead.y,ahead.z),gy=world.solidity(ahead.x,ahead.y+h,ahead.z)-world.solidity(ahead.x,ahead.y-h,ahead.z),gz=world.solidity(ahead.x,ahead.y,ahead.z+h)-world.solidity(ahead.x,ahead.y,ahead.z-h);acc.add(_v.set(-gx,-gy+0.4,-gz).normalize().multiplyScalar(cruise*7))}for(const o of others){if(o===this)continue;const d=this.pos.distanceTo(o.pos);if(d<this.L*1.8&&d>0.001)acc.add(_v.copy(this.pos).sub(o.pos).multiplyScalar((cruise*2.2)/d))}this.nextBurst-=dt;if(this.nextBurst<=0){this.burst=0.5+Math.random()*0.8;this.nextBurst=3+Math.random()*9}const burstK=this.burst>0?1+1.4*bold:1;if(this.burst>0)this.burst-=dt;this.vel.addScaledVector(acc,dt);const speed=this.vel.length(),target=cruise*burstK;if(speed>0.001)this.vel.multiplyScalar(THREE.MathUtils.lerp(speed,target,0.06)/speed);this.pos.addScaledVector(this.vel,dt);world.containment(this.pos.x,this.pos.y,this.pos.z,this.L*0.55,_corr);if(_corr.lengthSq()>0){this.pos.add(_corr);this.vel.addScaledVector(_corr,6)}this.mesh.position.copy(this.pos);_v.copy(this.pos).addScaledVector(this.vel,1);_m.lookAt(_v,this.pos,UP);_q.setFromRotationMatrix(_m);this.mesh.quaternion.slerp(_q,Math.min(1,dt*3.2));const freq=3.4+(this.vel.length()/Math.max(cruise,0.001))*2.6;for(const m of this.mesh.userData.materials){m.uniforms.uTime.value=this.phase;m.uniforms.uFreq.value=freq;m.uniforms.uAmp.value=this.L*0.055}}}
