// Twin Engine 0.5.0 geometry-hull.js
// Reconstructs rock volumes from front/top/side silhouettes using signed fields and surface nets.

function hash3(i,j,k){let h=i*374761393+j*668265263+k*2147483647;h=(h^(h>>13))*1274126177;return((h^(h>>16))>>>0)/4294967295}
function grad(i,j,k,x,y,z){const a=hash3(i,j,k)*6.2831853,b=hash3(i+71,j+17,k+131)*3.14159265;const gx=Math.cos(a)*Math.sin(b),gy=Math.sin(a)*Math.sin(b),gz=Math.cos(b);return gx*x+gy*y+gz*z}
const fade=t=>t*t*t*(t*(t*6-15)+10),lerp=(a,b,t)=>a+(b-a)*t;
export function noise3(x,y,z){const i=Math.floor(x),j=Math.floor(y),k=Math.floor(z),fx=x-i,fy=y-j,fz=z-k,u=fade(fx),v=fade(fy),w=fade(fz);const n000=grad(i,j,k,fx,fy,fz),n100=grad(i+1,j,k,fx-1,fy,fz),n010=grad(i,j+1,k,fx,fy-1,fz),n110=grad(i+1,j+1,k,fx-1,fy-1,fz),n001=grad(i,j,k+1,fx,fy,fz-1),n101=grad(i+1,j,k+1,fx-1,fy,fz-1),n011=grad(i,j+1,k+1,fx,fy-1,fz-1),n111=grad(i+1,j+1,k+1,fx-1,fy-1,fz-1);return lerp(lerp(lerp(n000,n100,u),lerp(n010,n110,u),v),lerp(lerp(n001,n101,u),lerp(n011,n111,u),v),w)}
export function fbm3(x,y,z,octaves=4){let sum=0,amp=1,freq=1,norm=0;for(let o=0;o<octaves;o++){sum+=amp*noise3(x*freq,y*freq,z*freq);norm+=amp;amp*=.5;freq*=2.03}return sum/norm}
export function ridged(x,y,z,octaves=4){let sum=0,amp=1,freq=1,norm=0;for(let o=0;o<octaves;o++){const n=1-Math.abs(noise3(x*freq,y*freq,z*freq));sum+=amp*(n*n);norm+=amp;amp*=.5;freq*=2.11}return sum/norm*2-1}
export function sdPolygon(pts,px,py){const n=pts.length;let dSq=Infinity,inside=false;for(let i=0,j=n-1;i<n;j=i++){const xi=pts[i][0],yi=pts[i][1],xj=pts[j][0],yj=pts[j][1],ex=xj-xi,ey=yj-yi,wx=px-xi,wy=py-yi,len2=ex*ex+ey*ey||1e-9;let t=(wx*ex+wy*ey)/len2;t=t<0?0:t>1?1:t;const dx=wx-ex*t,dy=wy-ey*t,d2=dx*dx+dy*dy;if(d2<dSq)dSq=d2;if((yi>py)!==(yj>py)&&px<((xj-xi)*(py-yi))/(yj-yi)+xi)inside=!inside}return(inside?1:-1)*Math.sqrt(dSq)}
function bounds(pts){let a=Infinity,b=-Infinity,c=Infinity,d=-Infinity;for(const p of pts){if(p[0]<a)a=p[0];if(p[0]>b)b=p[0];if(p[1]<c)c=p[1];if(p[1]>d)d=p[1]}return{min0:a,max0:b,min1:c,max1:d}}
export function buildIslandField(island){const s=island.silhouettes;if(!s||!s.front||!s.top||!s.side)throw new Error(`Isla "${island.id}": faltan siluetas (front/top/side).`);const e=island.erosion||{},ridgeScale=e.ridgeScale??.06,ridgeAmp=e.ridgeAmp??1,poreScale=e.poreScale??.45,poreAmp=e.poreAmp??.3,bf=bounds(s.front),bt=bounds(s.top),bs=bounds(s.side),pad=ridgeAmp+poreAmp+1,box={xMin:Math.max(bf.min0,bt.min0)-pad,xMax:Math.min(bf.max0,bt.max0)+pad,yMin:Math.max(bf.min1,bs.min1)-pad,yMax:Math.min(bf.max1,bs.max1)+pad,zMin:Math.max(bt.min1,bs.min0)-pad,zMax:Math.min(bt.max1,bs.max0)+pad},voids=(island.voids||[]).map(v=>({polygon:v.polygon,plane:v.plane||'front',range:v.range||[-99,99]})),seed=island.id.length*13.7;function field(x,y,z){let f=sdPolygon(s.front,x,y),t=sdPolygon(s.top,x,z);if(t<f)f=t;const d=sdPolygon(s.side,z,y);if(d<f)f=d;if(f<-pad*2)return f;for(const v of voids){let a,b,axis;if(v.plane==='front'){a=x;b=y;axis=z}else if(v.plane==='top'){a=x;b=z;axis=y}else{a=z;b=y;axis=x}const inSection=sdPolygon(v.polygon,a,b),slab=Math.min(axis-v.range[0],v.range[1]-axis),inVoid=Math.min(inSection,slab);if(-inVoid<f)f=-inVoid}f+=ridged((x+seed)*ridgeScale,(y-seed)*ridgeScale,(z+seed*.5)*ridgeScale,4)*ridgeAmp;f+=fbm3(x*poreScale,y*poreScale,z*poreScale,3)*poreAmp;return f}return{field,box}}
const CUBE_EDGES=[[0,1],[2,3],[4,5],[6,7],[0,2],[1,3],[4,6],[5,7],[0,4],[1,5],[2,6],[3,7]];
export function surfaceNets(field,box,res){const nx=Math.max(2,Math.ceil((box.xMax-box.xMin)/res)+1),ny=Math.max(2,Math.ceil((box.yMax-box.yMin)/res)+1),nz=Math.max(2,Math.ceil((box.zMax-box.zMin)/res)+1),at=(i,j,k)=>(k*ny+j)*nx+i,values=new Float32Array(nx*ny*nz);for(let k=0;k<nz;k++){const z=box.zMin+k*res;for(let j=0;j<ny;j++){const y=box.yMin+j*res;for(let i=0;i<nx;i++)values[at(i,j,k)]=field(box.xMin+i*res,y,z)}}const cellVertex=new Int32Array((nx-1)*(ny-1)*(nz-1)).fill(-1),cellAt=(i,j,k)=>(k*(ny-1)+j)*(nx-1)+i,positions=[];for(let k=0;k<nz-1;k++)for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const c=[values[at(i,j,k)],values[at(i+1,j,k)],values[at(i,j+1,k)],values[at(i+1,j+1,k)],values[at(i,j,k+1)],values[at(i+1,j,k+1)],values[at(i,j+1,k+1)],values[at(i+1,j+1,k+1)]];let pos=0;for(let n=0;n<8;n++)if(c[n]>0)pos++;if(pos===0||pos===8)continue;let sx=0,sy=0,sz=0,count=0;for(const[a,b]of CUBE_EDGES){const va=c[a],vb=c[b];if((va>0)===(vb>0))continue;const t=va/(va-vb),ax=a&1,ay=(a>>1)&1,az=(a>>2)&1,bx=b&1,by=(b>>1)&1,bz=(b>>2)&1;sx+=ax+(bx-ax)*t;sy+=ay+(by-ay)*t;sz+=az+(bz-az)*t;count++}cellVertex[cellAt(i,j,k)]=positions.length/3;positions.push(box.xMin+(i+sx/count)*res,box.yMin+(j+sy/count)*res,box.zMin+(k+sz/count)*res)}const vcount=positions.length/3,normals=new Float32Array(vcount*3),h=res*.5;for(let v=0;v<vcount;v++){const x=positions[v*3],y=positions[v*3+1],z=positions[v*3+2];let gx=field(x+h,y,z)-field(x-h,y,z),gy=field(x,y+h,z)-field(x,y-h,z),gz=field(x,y,z+h)-field(x,y,z-h),len=Math.hypot(gx,gy,gz)||1;normals[v*3]=gx/len;normals[v*3+1]=gy/len;normals[v*3+2]=gz/len}const indices=[],pushQuad=(a,b,c,d)=>{if(a<0||b<0||c<0||d<0)return;const ax=positions[a*3],ay=positions[a*3+1],az=positions[a*3+2],bx=positions[b*3]-ax,by=positions[b*3+1]-ay,bz=positions[b*3+2]-az,cx=positions[c*3]-ax,cy=positions[c*3+1]-ay,cz=positions[c*3+2]-az,fx=by*cz-bz*cy,fy=bz*cx-bx*cz,fz=bx*cy-by*cx,dot=fx*normals[a*3]+fy*normals[a*3+1]+fz*normals[a*3+2];if(dot>=0)indices.push(a,b,c,a,c,d);else indices.push(a,c,b,a,d,c)};for(let k=1;k<nz-1;k++)for(let j=1;j<ny-1;j++)for(let i=0;i<nx-1;i++){if((values[at(i,j,k)]>0)===(values[at(i+1,j,k)]>0))continue;pushQuad(cellVertex[cellAt(i,j-1,k-1)],cellVertex[cellAt(i,j,k-1)],cellVertex[cellAt(i,j,k)],cellVertex[cellAt(i,j-1,k)])}for(let k=1;k<nz-1;k++)for(let j=0;j<ny-1;j++)for(let i=1;i<nx-1;i++){if((values[at(i,j,k)]>0)===(values[at(i,j+1,k)]>0))continue;pushQuad(cellVertex[cellAt(i-1,j,k-1)],cellVertex[cellAt(i,j,k-1)],cellVertex[cellAt(i,j,k)],cellVertex[cellAt(i-1,j,k)])}for(let k=0;k<nz-1;k++)for(let j=1;j<ny-1;j++)for(let i=1;i<nx-1;i++){if((values[at(i,j,k)]>0)===(values[at(i,j,k+1)]>0))continue;pushQuad(cellVertex[cellAt(i-1,j-1,k)],cellVertex[cellAt(i,j-1,k)],cellVertex[cellAt(i,j,k)],cellVertex[cellAt(i-1,j,k)])}return{positions:new Float32Array(positions),normals,indices}}
export function cavityOpenness(field,x,y,z,nx,ny,nz){let open=0;for(const r of[1,2.2,4])if(field(x+nx*r,y+ny*r,z+nz*r)<0)open+=1;return open/3}
