import * as THREE from 'https://unpkg.com/three@0.169.0/build/three.module.js';
export function installGuidance(twin,host){
  const g=new THREE.Group();g.name='guidance';twin.scene.add(g);let note=null;
  function clear(){while(g.children.length)g.remove(g.children[0]);note?.remove();note=null}
  function label(text){note=document.createElement('div');note.textContent=text;note.style.cssText='position:absolute;top:92px;left:50%;transform:translateX(-50%);z-index:90;max-width:88%;padding:9px 13px;border-radius:14px;background:rgba(5,25,33,.94);border:1px solid rgba(201,255,249,.45);color:#fff;font:800 11px/1.35 system-ui;text-align:center;box-shadow:0 8px 24px rgba(0,0,0,.35)';host.appendChild(note)}
  function zone(position=[20,.4,12],size=[24,.7,14],text='Zona de trabajo',view='front'){clear();const geo=new THREE.BoxGeometry(...size),mat=new THREE.MeshBasicMaterial({color:0x49e7db,transparent:true,opacity:.27,depthWrite:false}),box=new THREE.Mesh(geo,mat);box.position.fromArray(position);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0xc9fff9}));edges.position.copy(box.position);g.add(box,edges);label(text);twin.setView?.(view)}
  function point(position=[0,20,0],text='Punto indicado',view='front'){clear();const p=new THREE.Vector3().fromArray(position);const ring=new THREE.Mesh(new THREE.TorusGeometry(4.2,.65,10,32),new THREE.MeshBasicMaterial({color:0xffd65a,depthWrite:false}));ring.position.copy(p);ring.rotation.x=Math.PI/2;const stem=new THREE.Mesh(new THREE.CylinderGeometry(.32,.32,12,8),new THREE.MeshBasicMaterial({color:0xffd65a}));stem.position.copy(p).add(new THREE.Vector3(0,6,0));const cone=new THREE.Mesh(new THREE.ConeGeometry(1.8,4,12),new THREE.MeshBasicMaterial({color:0xffd65a}));cone.position.copy(p).add(new THREE.Vector3(0,1.8,0));cone.rotation.z=Math.PI;g.add(ring,stem,cone);label(text);twin.setView?.(view)}
  function flow(position=[38,24,-6],direction=[-1,0,.25],text='Orientación propuesta',view='front'){clear();const origin=new THREE.Vector3().fromArray(position),dir=new THREE.Vector3().fromArray(direction).normalize();const arrow=new THREE.ArrowHelper(dir,origin,38,0x62e9ff,7,4);g.add(arrow);label(text);twin.setView?.(view)}
  twin.highlightMaintenanceZone=zone;twin.highlightPoint=point;twin.highlightFlow=flow;twin.clearGuidance=clear;
  return{zone,point,flow,clear,dispose(){clear();twin.scene.remove(g)}}
}
