import * as THREE from 'https://unpkg.com/three@0.169.0/build/three.module.js';

export function frontArc(tank){const a=tank.outerWidth/2,s=tank.frontBow,R=(a*a+s*s)/(2*s),apex=tank.frontEdgeZ+s,zc=apex-R;return{R,zc,apex,halfWidth:a}}
export function footprintPath(tank,inset=0,segments=64){const{R,zc,halfWidth}=frontArc(tank),hw=halfWidth-inset,zBack=-tank.outerDepth/2+inset,Ri=R-inset,pts=[new THREE.Vector2(-hw,zBack),new THREE.Vector2(hw,zBack)];for(let i=0;i<=segments;i++){const x=hw-(2*hw*i)/segments,inner=Math.max(0,Ri*Ri-x*x);pts.push(new THREE.Vector2(x,zc+Math.sqrt(inner)))}return pts}
function shapeFromPath(pts){const s=new THREE.Shape();s.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)s.lineTo(pts[i].x,pts[i].y);s.closePath();return s}
function reversedShape(pts){const s=new THREE.Shape(),r=[...pts].reverse();s.moveTo(r[0].x,r[0].y);for(let i=1;i<r.length;i++)s.lineTo(r[i].x,r[i].y);s.closePath();return s}
function extrudeUp(shape,height,hole){if(hole)shape.holes.push(hole);const g=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false,curveSegments:32});g.rotateX(-Math.PI/2);g.translate(0,height,0);return g}
function makeCurvedRail(tank,y,height,color=0xf1f3f3){const outer=shapeFromPath(footprintPath(tank,-0.5,72)),inner=reversedShape(footprintPath(tank,1.1,72)),geo=extrudeUp(outer,height,inner),mat=new THREE.MeshStandardMaterial({color,roughness:.44,metalness:.03});const m=new THREE.Mesh(geo,mat);m.position.y=y;return m}
function makeFrontGlass(tank){const{R,zc,halfWidth}=frontArc(tank),curve=new THREE.Curve();curve.getPoint=t=>{const x=THREE.MathUtils.lerp(-halfWidth,halfWidth,t),z=zc+Math.sqrt(Math.max(0,R*R-x*x));return new THREE.Vector3(x,0,z)};const path=new THREE.CatmullRomCurve3(Array.from({length:49},(_,i)=>curve.getPoint(i/48)));const profile=new THREE.Shape();profile.moveTo(-.08,0);profile.lineTo(.08,0);profile.lineTo(.08,tank.outerHeight-tank.rimHeight);profile.lineTo(-.08,tank.outerHeight-tank.rimHeight);profile.closePath();const geo=new THREE.ExtrudeGeometry(profile,{steps:96,bevelEnabled:false,extrudePath:path});const mat=new THREE.MeshPhysicalMaterial({color:0xd9f6ff,transparent:true,opacity:.045,roughness:.05,metalness:0,transmission:.82,thickness:.12,depthWrite:false,side:THREE.DoubleSide});const m=new THREE.Mesh(geo,mat);m.name='curved-front-glass';m.renderOrder=8;return m}
export function buildTank(tank,quality,resolution){
  const group=new THREE.Group();group.name='tank';const t=tank.glassThickness;
  const baseGeo=extrudeUp(shapeFromPath(footprintPath(tank,0,64)),t);const base=new THREE.Mesh(baseGeo,new THREE.MeshStandardMaterial({color:0xe9eceb,roughness:.5}));base.position.y=-t;group.add(base);
  const bottomRail=makeCurvedRail(tank,0,1.15,0xf2f2ef);bottomRail.name='white-bottom-rail';group.add(bottomRail);
  const topRail=makeCurvedRail(tank,tank.outerHeight-2.1,2.1,0xf4f4f1);topRail.name='white-top-rail';group.add(topRail);
  const lid=makeCurvedRail(tank,tank.outerHeight-.45,.45,0xf7f7f4);lid.name='white-lid-frame';group.add(lid);
  const glass=makeFrontGlass(tank);group.add(glass);
  const chamberZ=-tank.outerDepth/2+tank.rearChamberDepth;
  const chamber=new THREE.Mesh(new THREE.PlaneGeometry(tank.outerWidth-1.5,tank.outerHeight-4),new THREE.MeshStandardMaterial({color:0x111b20,roughness:.82,side:THREE.DoubleSide}));chamber.position.set(0,(tank.outerHeight-4)/2+1.2,chamberZ);chamber.name='rear-chamber';group.add(chamber);
  const waterGeo=new THREE.ShapeGeometry(shapeFromPath(footprintPath(tank,t+.15,72)),32);waterGeo.rotateX(-Math.PI/2);const waterMat=new THREE.MeshPhysicalMaterial({color:0x7fc7da,transparent:true,opacity:.12,roughness:.08,metalness:0,depthWrite:false,side:THREE.DoubleSide});waterMat.userData.uniforms={uTime:{value:0}};waterMat.onBeforeCompile=shader=>{shader.uniforms.uTime=waterMat.userData.uniforms.uTime;shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nuniform float uTime;').replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.y += sin(position.x*0.27 + uTime*1.0)*0.12 + sin(position.z*0.43-uTime*.7)*0.08;')};const water=new THREE.Mesh(waterGeo,waterMat);water.position.y=tank.waterLevel;water.renderOrder=7;group.add(water);
  const{R,zc,halfWidth}=frontArc(tank),inset=t+.4;
  function insideWater(x,y,z,margin=0){const m=inset+margin;if(y<margin||y>tank.waterLevel-margin)return false;if(Math.abs(x)>halfWidth-m)return false;if(z<chamberZ+m)return false;return Math.hypot(x,z-zc)<R-m}
  function containment(x,y,z,margin,out){out.set(0,0,0);const m=inset+margin,hx=halfWidth-m;if(x>hx)out.x-=x-hx;if(x<-hx)out.x-=x+hx;if(y<margin)out.y+=margin-y;const top=tank.waterLevel-margin;if(y>top)out.y-=y-top;const zb=chamberZ+m;if(z<zb)out.z+=zb-z;const dz=z-zc,d=Math.hypot(x,dz),lim=R-m;if(d>lim){const k=(d-lim)/(d||1);out.x-=x*k;out.z-=dz*k}return out}
  return{group,glass,water,glassMaterial:glass.material,materials:[waterMat],insideWater,containment,chamberZ,frontApexZ:zc+R,center:new THREE.Vector3(0,17,0),outerRadius:Math.max(halfWidth,tank.outerDepth/2)+6}
}
