import * as THREE from 'https://unpkg.com/three@0.169.0/build/three.module.js';

export function frontArc(tank){const a=tank.outerWidth/2,s=tank.frontBow,R=(a*a+s*s)/(2*s),apex=tank.frontEdgeZ+s,zc=apex-R;return{R,zc,apex,halfWidth:a}}
export function footprintPath(tank,inset=0,segments=48){const{R,zc,halfWidth}=frontArc(tank),hw=halfWidth-inset,zBack=-tank.outerDepth/2+inset,Ri=R-inset,pts=[new THREE.Vector2(-hw,zBack),new THREE.Vector2(hw,zBack)];for(let i=0;i<=segments;i++){const x=hw-2*hw*i/segments;pts.push(new THREE.Vector2(x,zc+Math.sqrt(Math.max(0,Ri*Ri-x*x))))}return pts}
function shapeFromPath(pts){const s=new THREE.Shape();s.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)s.lineTo(pts[i].x,pts[i].y);s.closePath();return s}
function reversedShape(pts){const s=new THREE.Shape(),r=[...pts].reverse();s.moveTo(r[0].x,r[0].y);for(let i=1;i<r.length;i++)s.lineTo(r[i].x,r[i].y);s.closePath();return s}
function extrudeUp(shape,height,hole){if(hole)shape.holes.push(hole);const g=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false,curveSegments:32});g.rotateX(-Math.PI/2);g.translate(0,height,0);return g}
function safeGlass(){return new THREE.MeshPhysicalMaterial({color:0xc9edf4,transparent:true,opacity:.11,roughness:.05,metalness:0,transmission:0.72,thickness:.45,ior:1.33,depthWrite:false,side:THREE.DoubleSide})}
export function buildTank(tank,quality,resolution){
 const group=new THREE.Group();group.name='tank';const t=tank.glassThickness,outer=footprintPath(tank,0),inner=footprintPath(tank,t);
 const wallGeo=extrudeUp(shapeFromPath(outer),tank.outerHeight-tank.rimHeight,reversedShape(inner));const glassMat=safeGlass(),glass=new THREE.Mesh(wallGeo,glassMat);glass.name='glass';glass.renderOrder=20;group.add(glass);
 const white=new THREE.MeshStandardMaterial({color:0xf4f3ee,roughness:.38,metalness:.04});
 const base=new THREE.Mesh(extrudeUp(shapeFromPath(outer),t),white);base.position.y=-t;group.add(base);
 const rim=new THREE.Mesh(extrudeUp(shapeFromPath(footprintPath(tank,-.45)),tank.rimHeight,reversedShape(footprintPath(tank,t))),white);rim.position.y=tank.outerHeight-tank.rimHeight;group.add(rim);
 // Fluval Flex Marine 123 visual identity: white curved top hood/lid following the bowed front footprint.
 const hoodShape=shapeFromPath(footprintPath(tank,-.65));const hood=new THREE.Mesh(extrudeUp(hoodShape,1.15),white);hood.position.y=tank.outerHeight+.18;hood.name='white-hood';group.add(hood);
 const lidInner=shapeFromPath(footprintPath(tank,1.2));const lid=new THREE.Mesh(new THREE.ShapeGeometry(lidInner,32),new THREE.MeshStandardMaterial({color:0xf7f6f1,roughness:.5,transparent:true,opacity:.82,side:THREE.DoubleSide}));lid.rotateX(-Math.PI/2);lid.position.y=tank.outerHeight+.12;lid.name='white-lid';group.add(lid);
 const chamberZ=-tank.outerDepth/2+tank.rearChamberDepth;const chamber=new THREE.Mesh(new THREE.PlaneGeometry(tank.outerWidth-2*t,tank.outerHeight-2),new THREE.MeshStandardMaterial({color:0x101417,roughness:.75,side:THREE.DoubleSide}));chamber.position.set(0,(tank.outerHeight-2)/2,chamberZ);group.add(chamber);
 const waterGeo=new THREE.ShapeGeometry(shapeFromPath(footprintPath(tank,t+.05)),32);waterGeo.rotateX(-Math.PI/2);const waterMat=new THREE.MeshStandardMaterial({color:0x75c9df,transparent:true,opacity:.16,roughness:.12,side:THREE.DoubleSide,depthWrite:false});waterMat.userData.uniforms={uTime:{value:0}};waterMat.onBeforeCompile=s=>{s.uniforms.uTime=waterMat.userData.uniforms.uTime;s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nuniform float uTime;').replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.y+=sin(position.x*.35+uTime*1.1)*.16+sin(position.z*.5-uTime*.8)*.12;')};const water=new THREE.Mesh(waterGeo,waterMat);water.position.y=tank.waterLevel;group.add(water);
 const{R,zc,halfWidth}=frontArc(tank),inset=t+.4;function containment(x,y,z,margin,out){out.set(0,0,0);const m=inset+margin,hx=halfWidth-m;if(x>hx)out.x-=x-hx;if(x<-hx)out.x-=x+hx;if(y<margin)out.y+=margin-y;const top=tank.waterLevel-margin;if(y>top)out.y-=y-top;const zb=chamberZ+m;if(z<zb)out.z+=zb-z;const dz=z-zc,d=Math.hypot(x,dz),lim=R-m;if(d>lim){const k=(d-lim)/(d||1);out.x-=x*k;out.z-=dz*k}return out}
 return{group,glass,water,glassMaterial:glassMat,materials:[waterMat],containment,chamberZ,frontApexZ:zc+R,center:new THREE.Vector3(0,tank.outerHeight*.45,0),outerRadius:Math.max(halfWidth,tank.outerDepth/2)+6};
}
